export interface Review {
  id: string;
  authorNpub: string;
  rating: number;
  comment: string;
  date: string;
}

export interface Merchant {
  id: string;
  name: string;
  description: string;
  logo: string; // Emoji or initial for now
  categories: string[];
  shippingCountries: string[];
  website: string;
  lightningSupported: boolean;
  onchainSupported: boolean;
  paymentProvider?: string;
  reviews: Review[];
  featured?: boolean;
  countryMadeIn?: string;
  countryShippedFrom?: string;
}

export const PAYMENT_PROVIDERS = [
  "BTCPay Server",
  "Zaprite",
  "Strike",
  "OpenNode",
  "IBEX",
  "CoinCorner",
  "CoinGate"
];

export const CATEGORIES = [
  "💻 Electronics",
  "👕 Clothing",
  "🍴 Food & Drink",
  "✈️ Travel",
  "🎁 Gift Cards",
  "🛡️ VPN & Privacy",
  "🌐 Hosting",
  "📚 Books",
  "🎨 Art",
  "❤️ Charity"
];

export const COUNTRIES = [
  "🌍 Worldwide",
  "🇺🇸 USA",
  "🇪🇺 Europe",
  "🇨🇦 Canada",
  "🇬🇧 UK",
  "🇦🇺 Australia",
  "🇸🇻 El Salvador",
  "🇸🇪 Sweden"
];

export const MOCK_MERCHANTS: Merchant[] = [
  {
    id: "1",
    name: "BitRefill",
    description: "Buy Gift Cards & Mobile Refills with Bitcoin. Live on crypto.",
    logo: "/assets/bitrefill-logo.png",
    categories: ["Gift Cards", "Travel"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://bitrefill.com",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    featured: true,
    reviews: [
      { id: "r1", authorNpub: "npub1...xyz", rating: 5, comment: "Works instantly via Lightning!", date: "2024-03-10" },
      { id: "r2", authorNpub: "npub1...abc", rating: 5, comment: "Essential for living on Bitcoin.", date: "2024-02-15" }
    ]
  },
  {
    id: "2",
    name: "SLNT",
    description: "Privacy-first Faraday bags and signal blocking accessories.",
    logo: "/assets/slnt-logo.png",
    categories: ["💻 Electronics"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://slnt.com",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "Zaprite",
    countryShippedFrom: "USA",
    countryMadeIn: "USA",
    reviews: [
      { id: "r3", authorNpub: "npub1...def", rating: 5, comment: "High quality signal blocking gear.", date: "2024-01-20" }
    ]
  },
  {
    id: "3",
    name: "Mullvad VPN",
    description: "Mullvad is a VPN service that helps keep your online activity, identity, and location private.",
    logo: "/assets/mullvad-logo.png",
    categories: ["🛡️ VPN & Privacy"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://mullvad.net",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "Strike",
    countryShippedFrom: "Sweden",
    countryMadeIn: "Sweden",
    featured: true,
    reviews: [
      { id: "r4", authorNpub: "npub1...ghi", rating: 5, comment: "Best privacy VPN, accepts cash and BTC.", date: "2024-03-01" }
    ]
  },
  {
    id: "4",
    name: "Coinkite",
    description: "Hardware wallets for Bitcoin security. Makers of Coldcard.",
    logo: "/assets/coinkite-logo.png",
    categories: ["💻 Electronics"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://coinkite.com",
    lightningSupported: true,
    onchainSupported: true,
    countryShippedFrom: "Canada",
    countryMadeIn: "Canada",
    reviews: []
  },
  {
    id: "5",
    name: "Start9",
    description: "Sovereign computing. Run your own personal server.",
    logo: "/assets/start9-logo.png",
    categories: ["💻 Electronics", "🌐 Hosting"],
    shippingCountries: ["🌍 Worldwide", "🇺🇸 USA"],
    website: "https://start9.com",
    lightningSupported: true,
    onchainSupported: true,
    featured: true,
    reviews: []
  },
  {
    id: "6",
    name: "Daylight Computer",
    description: "Building the first computer that feels like paper. The Daylight Tablet.",
    logo: "/assets/daylight-logo.png",
    categories: ["💻 Electronics"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://daylightcomputer.com",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "7",
    name: "Tor Project",
    description: "Defending your rights to privacy and freedom online. Help us keep Tor strong.",
    logo: "/assets/tor-logo-new.png",
    categories: ["🛡️ VPN & Privacy", "❤️ Charity"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://torproject.org",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "8",
    name: "Namecheap",
    description: "Register domains and buy web hosting with Bitcoin. Privacy-focused domain registrar.",
    logo: "/assets/namecheap-logo.png",
    categories: ["🌐 Hosting"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://namecheap.com",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "9",
    name: "Human Rights Foundation",
    description: "Supporting civil society in closed societies and uniting people in the common cause of human rights.",
    logo: "/assets/hrf-logo.png",
    categories: ["❤️ Charity"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://hrf.org",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "10",
    name: "CheapAir",
    description: "Book flights and hotels with Bitcoin. One of the first travel sites to accept BTC.",
    logo: "/assets/cheapair-logo.png",
    categories: ["✈️ Travel"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://cheapair.com",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "11",
    name: "Travala",
    description: "Book 3,000,000+ travel products worldwide with Bitcoin and other cryptocurrencies.",
    logo: "/assets/travala-logo-new.png",
    categories: ["✈️ Travel"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://travala.com",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "12",
    name: "G2A",
    description: "The world's largest marketplace for digital entertainment. Buy games, gift cards, and software with Bitcoin.",
    logo: "/assets/g2a-logo-new.png",
    categories: ["🎁 Gift Cards"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://g2a.com",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "13",
    name: "Obscura",
    description: "High-performance VPN service built for the Bitcoin ecosystem. Privacy without compromise.",
    logo: "/assets/obscura-logo-new.png",
    categories: ["🛡️ VPN & Privacy"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://obscuravpn.com",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "14",
    name: "Silent.link",
    description: "Anonymously purchase eSIMs with Bitcoin. Privacy-first mobile data and SMS services.",
    logo: "/assets/silent-link-logo-new.png",
    categories: ["🛡️ VPN & Privacy"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://silent.link",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "15",
    name: "Great Ghee",
    description: "Handcrafted, small-batch ghee made from grass-fed butter. High-quality clarified butter for healthy cooking.",
    logo: "/assets/great-ghee-clean.png",
    categories: ["🍴 Food & Drink"],
    shippingCountries: ["🇺🇸 USA"],
    website: "https://greatghee.com",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "16",
    name: "Great North Air Ambulance",
    description: "Life-saving charity providing emergency medical care across the North of England. Supporting their operations via Bitcoin donations.",
    logo: "/assets/gnaas-logo-new.png",
    categories: ["❤️ Charity"],
    shippingCountries: ["🇬🇧 UK"],
    website: "https://www.greatnorthairambulance.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "17",
    name: "Castle Hill Gin",
    description: "Premium handcrafted gin distilled in the heart of Yorkshire. Traditional methods with modern botanical blends.",
    logo: "/assets/castle-hill-gin-new.png",
    categories: ["🍴 Food & Drink"],
    shippingCountries: ["🇬🇧 UK"],
    website: "https://www.castlehillgin.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "18",
    name: "Bonjour Wines",
    description: "Specialist importer of fine French wines and artisanal spirits. Discover a curated selection of exceptional vineyards.",
    logo: "/assets/bonjour-wines-new.png",
    categories: ["🍴 Food & Drink"],
    shippingCountries: ["🇬🇧 UK"],
    website: "https://www.bonjourwines.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "19",
    name: "Peony Lane Wine",
    description: "Artisan winery specializing in elegant, floral-noted wines. Experience the unique terroir of our boutique vineyards.",
    logo: "/assets/peony-lane-new.png",
    categories: ["🍴 Food & Drink"],
    shippingCountries: ["🇺🇸 USA"],
    website: "https://www.peonylanewine.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "20",
    name: "Yum Yum Tree Fudge",
    description: "Premium handcrafted fudge made with natural ingredients. Discover a vast array of unique and traditional flavors from this artisan confectioner.",
    logo: "/assets/yum-yum-tree-fudge-new.png",
    categories: ["🍴 Food & Drink"],
    shippingCountries: ["🇬🇧 UK", "🌍 Worldwide"],
    website: "https://www.yumyumtreefudge.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "21",
    name: "Tea and Tonic",
    description: "British luxury skincare and wellness brand using high-performance adaptogens and sustainable ingredients to support body and mind.",
    logo: "/assets/tea-and-tonic-new.png",
    categories: ["✨ Lifestyle"],
    shippingCountries: ["🇬🇧 UK", "🌍 Worldwide"],
    website: "https://www.teaandtonic.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "22",
    name: "AroTags",
    description: "Premium wood air fresheners for your car. Long-lasting, artisan-crafted scents using high-quality essential oils.",
    logo: "/assets/arotags-new.png",
    categories: ["🚗 Auto", "✨ Lifestyle"],
    shippingCountries: ["🇺🇸 USA", "🌍 Worldwide"],
    website: "https://www.arotags.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "23",
    name: "Spitting Feathers",
    description: "Award-winning independent brewery and pub. Crafting exceptional real ales and craft beers with a focus on quality and tradition.",
    logo: "/assets/spitting-feathers-fox.png",
    categories: ["🍴 Food & Drink"],
    shippingCountries: ["🇬🇧 UK"],
    website: "https://spittingfeathers.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "24",
    name: "Mushmore Supplements",
    description: "Premium mushroom supplements crafted for optimal wellness. Harnessing the power of functional fungi for clarity, focus, and vitality.",
    logo: "/assets/mushmore-logo.png",
    categories: ["🍴 Food & Drink"],
    shippingCountries: ["🇺🇸 USA", "🌍 Worldwide"],
    website: "https://www.mushmoresupplements.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "25",
    name: "Hummingbird Amsterdam",
    description: "Specialty coffee bar and store in the heart of Amsterdam. Discover a curated selection of coffee beans and brewing equipment.",
    logo: "/assets/hummingbird-logo.png",
    categories: ["🍴 Food & Drink"],
    shippingCountries: ["🇳🇱 Netherlands", "🇪🇺 Europe"],
    website: "https://www.hummingbird.amsterdam/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "26",
    name: "Planet Express",
    description: "Your premier package forwarding and shipping partner. Ship from the USA to anywhere in the world with ease and reliability.",
    logo: "/assets/planet-express-logo.png",
    categories: ["✨ Lifestyle"],
    shippingCountries: ["🇺🇸 USA", "🌍 Worldwide"],
    website: "https://planetexpress.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "27",
    name: "Farfetch",
    description: "The global destination for modern luxury. Shop the world's best designers and boutiques for clothing, shoes, and accessories.",
    logo: "/assets/farfetch-logo.png",
    categories: ["👗 Fashion"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.farfetch.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "28",
    name: "Bramleigh Farm",
    description: "Family-run regenerative farm in the KZN Midlands. Premium pasture-raised chicken, eggs, pork, and grass-fed beef delivered direct to your door.",
    logo: "/assets/bramleigh-logo.png",
    categories: ["🍴 Food & Drink"],
    shippingCountries: ["🇿🇦 South Africa"],
    website: "https://www.bramleigh.co.za/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "29",
    name: "Oshi Good",
    description: "Specialty coffee and cafe goods. Discover premium coffee beans and accessories for the perfect home brewing experience.",
    logo: "/assets/oshi-new.png",
    categories: ["🍴 Food & Drink"],
    shippingCountries: ["🇺🇸 USA"],
    website: "https://www.oshigood.us/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "30",
    name: "Palingshop",
    description: "Traditional Dutch smoked eel and premium seafood delicacies delivered fresh from Volendam. Experience authentic Dutch flavors.",
    logo: "/assets/palingshop-logo.png",
    categories: ["🍴 Food & Drink"],
    shippingCountries: ["🇳🇱 Netherlands", "🇪🇺 Europe"],
    website: "https://www.palingshop.nl/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "31",
    name: "Ticketpro",
    description: "South Africa's leading ticketing provider for sports, concerts, and events. Book your next experience with Bitcoin.",
    logo: "/assets/ticketpro-logo.png",
    categories: ["🎬 Entertainment"],
    shippingCountries: ["🇿🇦 South Africa"],
    website: "https://www.ticketpro.co.za/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "32",
    name: "Dynadot",
    description: "Affordable domain registration and hosting services. Manage your digital identity with ease and security.",
    logo: "/assets/dynadot-logo.png",
    categories: ["🌐 Hosting"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.dynadot.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "33",
    name: "Soapminer",
    description: "Handcrafted natural soaps for Bitcoiners. High-quality ingredients and unique designs that celebrate the Bitcoin lifestyle.",
    logo: "/assets/soapminer-logo.png",
    categories: ["💄 Health & Beauty", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://soapminer.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "34",
    name: "MobiMatter",
    description: "The best eSIM marketplace for travelers. Get instant connectivity worldwide with affordable data plans.",
    logo: "/assets/mobimatter-logo.png",
    categories: ["✈️ Travel", "⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://mobimatter.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "35",
    name: "The Good Beans",
    description: "Ethically sourced, freshly roasted specialty coffee. Discover a wide variety of unique blends and single-origin beans.",
    logo: "/assets/thegoodbeans-logo.png",
    categories: ["🍴 Food & Drink"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://thegoodbeans.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "36",
    name: "Pumphreys Coffee",
    description: "Multi-award winning coffee roasters based in the North East of England since 1750. Specialists in finest quality coffee and tea.",
    logo: "/assets/pumphreys-logo.png",
    categories: ["🍴 Food & Drink"],
    shippingCountries: ["🇬🇧 UK", "🌍 Worldwide"],
    website: "https://pumphreys-coffee.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "38",
    name: "Epic Deals",
    description: "South Africa's leading platform for pre-owned and new tech. Shop smartphones, tablets, and more with Bitcoin.",
    logo: "/assets/epicdeals-logo.png",
    categories: ["💻 Electronics"],
    shippingCountries: ["🇿🇦 South Africa"],
    website: "https://epicdeals.co.za/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "39",
    name: "Farmer Bill's Provisions",
    description: "Premium, craft beef jerky and meat snacks. Ethically sourced and packed with flavor, delivered to your door.",
    logo: "/assets/farmerbills-logo.png",
    categories: ["🍴 Food & Drink"],
    shippingCountries: ["🇺🇸 USA"],
    website: "https://farmerbillsprovisions.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "40",
    name: "Acme Acres",
    description: "Pasture-raised heritage pork and poultry from a family-owned farm. Focused on ethical farming and sustainable practices.",
    logo: "/assets/acmeacres-logo.png",
    categories: ["🍴 Food & Drink"],
    shippingCountries: ["🇺🇸 USA"],
    website: "https://acmeacres.us/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "41",
    name: "Chroma",
    description: "Chroma is dedicated to staying on the cutting edge of light therapy. Your support pushes forward devices designed by engineers who care deeply about health.",
    logo: "/assets/chroma-new.png",
    categories: ["⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://getchroma.co/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "42",
    name: "Kawa",
    description: "Specialty coffee roastery offering unique and flavorful beans. Experience the art of Japanese-inspired coffee roasting.",
    logo: "/assets/kawa-new.png",
    categories: ["🍴 Food & Drink"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.u2kawa.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "43",
    name: "Kijicha",
    description: "Authentic Japanese tea and premium matcha sourced directly from growers. Experience the tradition and serenity of high-quality tea.",
    logo: "/assets/kijicha-new.png",
    categories: ["🍴 Food & Drink"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://kijicha.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "44",
    name: "Leeds Gin",
    description: "Premium gin hand crafted in small batches in the heart of Yorkshire. Traditional botanicals steeped with juniper, coriander, ginger and orange.",
    logo: "https://www.leedsgin.com/wp-content/uploads/elementor/thumbs/cropped-Favicon-v2-01-plyh4y2k69gla83ozhwxsz3smo2eeooufuj8remsgw.png",
    categories: ["🍴 Food & Drink", "🍷 Alcohol"],
    shippingCountries: ["🇬🇧 UK"],
    website: "https://www.leedsgin.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "45",
    name: "ASF Tutoring",
    description: "Online Maths tutor specialising in 1-1 and small group tuition. Empowering young people to have confidence in their mathematical ability.",
    logo: "/assets/asf-tutoring-new.png",
    categories: ["⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.asftutoring.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "46",
    name: "The Suffolk Tutor",
    description: "Personalised primary school tutoring and specialist SEND support. Qualified teacher offering one-to-one and group sessions in Maths, English, and Science.",
    logo: "https://static.wixstatic.com/media/e7f737_461ad44966af488b8bdfee9c8146a001~mv2.png/v1/fill/w_385,h_465,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/%40thesuffolktutor.png",
    categories: ["⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide", "🇬🇧 UK"],
    website: "https://www.thesuffolktutor.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "47",
    name: "Jimble's Jumble",
    description: "Homemade preserves created in Northamptonshire from homegrown, wild foraged and food rescued ingredients. Small-batch jams, chutneys, and marmalades.",
    logo: "https://jimblesjumble.odoo.com/web/image/3369-f7e687f9/3-DSC_0022.webp",
    categories: ["🍴 Food & Drink"],
    shippingCountries: ["🇬🇧 UK"],
    website: "https://jimblesjumble.odoo.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "48",
    name: "Hempful",
    description: "Premium European CBD and hemp products. High-potency, full-spectrum CBD oils, beverages, and skincare grown in the perfect climate for maximum potency.",
    logo: "/assets/hempful-new.png",
    categories: ["🍴 Food & Drink", "🧘 Wellness", "💄 Health & Beauty"],
    shippingCountries: ["🌍 Worldwide", "🇬🇧 UK", "🇪🇺 Europe"],
    website: "https://hempful.eu/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "49",
    name: "Highland Fayre",
    description: "Scotland's No. 1 specialist hamper company. Luxury food and wine hampers, gift baskets, and corporate gifts delivered throughout the UK.",
    logo: "/assets/highland-fayre-new.png",
    categories: ["🍴 Food & Drink", "🍷 Alcohol"],
    shippingCountries: ["🇬🇧 UK"],
    website: "https://www.highlandfayre.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "50",
    name: "Golden Tallow",
    description: "Luxurious skincare powered by pure Wagyu tallow. Nutrient-rich, artisanal formulations designed to restore and elevate your natural glow.",
    logo: "/assets/golden-tallow-logo.png",
    categories: ["💄 Health & Beauty", "🧘 Wellness"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://goldentallow.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "51",
    name: "Mister Padel",
    description: "Premium Padel equipment and apparel for enthusiasts of the fastest-growing racket sport. High-quality rackets, bags, and accessories for all skill levels.",
    logo: "/assets/mister-padel-icon.png",
    categories: ["⚽ Sports", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://misterpadel.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "52",
    name: "Lincoln Kiln Dried Logs",
    description: "Sustainable kiln-dried firewood delivered direct to your door. High-quality logs for stoves and open fires, sourced from managed woodlands.",
    logo: "/assets/lincoln-logs-logo.png",
    categories: ["✨ Lifestyle"],
    shippingCountries: ["🇬🇧 UK"],
    website: "https://www.lincolnkilndriedlogs.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "53",
    name: "Essatoshi",
    description: "Bitcoin-inspired apparel and goods for the sovereign individual. Unique designs that celebrate the Bitcoin revolution and cypherpunk culture.",
    logo: "/assets/essatoshi-logo.png",
    categories: ["👗 Fashion", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://essatoshi.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "54",
    name: "Cheerings",
    description: "Artisanal cocktail infusions and premium barware for the home mixologist. Elevate your hosting experience with our curated kits and accessories.",
    logo: "/assets/cheerings-logo-new.png",
    categories: ["🍴 Food & Drink", "🍷 Alcohol"],
    shippingCountries: ["🇺🇸 USA"],
    website: "https://cheerings.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "55",
    name: "Jonathan Hill Luthier",
    description: "Exquisite handcrafted guitars and professional lutherie services. Custom-built instruments designed for exceptional tone, playability, and beauty.",
    logo: "/assets/jonathan-hill-logo-new.png",
    categories: ["🎵 Music", "🎨 Art", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.jonathanhill.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "56",
    name: "Select Automotive",
    description: "Specialist automotive parts and accessories for performance and classic vehicles. Expert sourcing and supply of high-quality components.",
    logo: "/assets/select-automotive-logo-new.png",
    categories: ["🚗 Auto", "⚙️ Tech"],
    shippingCountries: ["🇬🇧 UK", "🇪🇺 Europe"],
    website: "https://select-automotive.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "57",
    name: "CandyJets",
    description: "Premium sweets and confectionery delivered globally. Discover a world of unique treats and nostalgic favorites from our curated selection.",
    logo: "/assets/candyjets-logo-black.png",
    categories: ["🍴 Food & Drink", "🍬 Sweets"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://candyjets.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "58",
    name: "Maple AI",
    description: "Cutting-edge AI solutions for business automation and data analysis. Empowering organizations with intelligent tools for growth and efficiency.",
    logo: "/assets/maple-ai-logo-new.png",
    categories: ["⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://maple.ai/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "59",
    name: "PayperQ",
    description: "Streamlined payment solutions for the digital economy. Facilitating secure and efficient transactions for businesses and consumers.",
    logo: "/assets/payperq-logo.png",
    categories: ["⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://payperq.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "60",
    name: "Crypto Tax Help",
    description: "Expert tax advisory services for cryptocurrency investors and businesses. Navigate the complexities of crypto taxation with confidence.",
    logo: "/assets/crypto-tax-help-logo-new.png",
    categories: ["⚙️ Tech"],
    shippingCountries: ["🇬🇧 UK"],
    website: "https://cryptotaxhelp.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "61",
    name: "MtSocks",
    description: "Limited edition Bitcoin-themed socks. High-quality apparel that helps you wear your Bitcoin pride and spread adoption.",
    logo: "/assets/mtsocks-new.png",
    categories: ["👗 Fashion", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.mtsocks.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "62",
    name: "TorGuard",
    description: "Anonymous VPN and proxy services for ultimate online privacy and security. Protect your data and bypass censorship with our high-speed network.",
    logo: "/assets/torguard-new.png",
    categories: ["🛡️ VPN & Privacy", "⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://torguard.net/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "63",
    name: "Beef Initiative",
    description: "Connecting consumers directly with local ranchers for high-quality, grass-fed beef. Supporting local food systems and sound money.",
    logo: "/assets/beef-initiative-logo.png",
    categories: ["🍴 Food & Drink", "✨ Lifestyle"],
    shippingCountries: ["🇺🇸 USA"],
    website: "https://beefinitiative.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "64",
    name: "Spy Equipment UK",
    description: "Professional grade surveillance and counter-surveillance equipment. High-quality security solutions for personal and professional use.",
    logo: "/assets/spy-equipment-new.png",
    categories: ["💻 Electronics", "⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.spyequipmentuk.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "65",
    name: "Bees & Trees",
    description: "Premium Manuka honey sourced directly from our own hives in New Zealand. Authentic, high-quality honey for wellness and culinary use.",
    logo: "/assets/bees-and-trees-logo.png",
    categories: ["🍴 Food & Drink", "🧘 Wellness"],
    shippingCountries: ["🇺🇸 USA", "🌍 Worldwide"],
    website: "https://www.beesandtrees.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "66",
    name: "Kaffebox",
    description: "Scandinavian specialty coffee subscription. Discover the best roasters from the Nordics delivered fresh to your door every month.",
    logo: "/assets/kaffebox-logo.png",
    categories: ["🍴 Food & Drink", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.kaffebox.no/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "67",
    name: "Bloom Audio",
    description: "High-end headphones and portable audio equipment for audiophiles. Expert advice and a curated selection of the world's best audio gear.",
    logo: "/assets/bloom-audio-logo.png",
    categories: ["💻 Electronics", "🎵 Music", "⚙️ Tech"],
    shippingCountries: ["🇺🇸 USA"],
    website: "https://bloomaudio.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "68",
    name: "La Industria Handmade",
    description: "Artisanal leather goods handcrafted in El Salvador. Unique, high-quality products that support local craftsmanship and economic freedom.",
    logo: "/assets/la-industria-logo.png",
    categories: ["👗 Fashion", "🎨 Art", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://laindustriahandmade.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "IBEX",
    reviews: []
  },
  {
    id: "69",
    name: "Campo Apícola",
    description: "Premium honey and bee products from El Salvador. Supporting sustainable beekeeping and local biodiversity through high-quality artisanal goods.",
    logo: "/assets/campo-apicola-v2.png",
    categories: ["🍴 Food & Drink", "🧘 Wellness", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://campoapicola.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "IBEX",
    reviews: []
  },
  {
    id: "70",
    name: "Elephant Chateau",
    description: "Exquisite Ceylon teas and spices sourced directly from Sri Lanka. Discover rare and flavorful blends that celebrate the heritage of fine tea.",
    logo: "/assets/elephant-chateau-v2.png",
    categories: ["🍴 Food & Drink", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://elephantchateau.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "OpenNode",
    reviews: []
  },
  {
    id: "71",
    name: "Árbol de Maple",
    description: "Premium maple syrup and specialty wood products from El Salvador. Blending traditional flavors with local craftsmanship for unique artisanal goods.",
    logo: "/assets/arbol-de-maple-new.png",
    categories: ["🍴 Food & Drink", "🎨 Art", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://arboldemaple.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "IBEX",
    reviews: []
  },
  {
    id: "72",
    name: "Consumer Choice Center",
    description: "A global non-profit advocacy group representing consumers in over 100 countries. Fighting for lifestyle freedom, innovation, and choice.",
    logo: "/assets/ccc-logo-new.png",
    categories: ["❤️ Charity", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://consumerchoicecenter.org/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "OpenNode",
    reviews: []
  },
  {
    id: "73",
    name: "Pikasim",
    description: "Global eSIM solutions for seamless international travel. Stay connected in over 150 countries with affordable and instant mobile data.",
    logo: "/assets/pikasim-new.png",
    categories: ["✈️ Travel", "⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://pikasim.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "IBEX",
    reviews: []
  },
  {
    id: "74",
    name: "Mad Gringo Hot Sauce",
    description: "Artisanal hot sauces with bold flavors and a serious kick. Handcrafted in small batches for the ultimate spicy experience.",
    logo: "/assets/mad-gringo-new.png",
    categories: ["🍴 Food & Drink", "✨ Lifestyle"],
    shippingCountries: ["🇺🇸 USA"],
    website: "https://madgringo.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "75",
    name: "PrivateRouter",
    description: "Privacy-focused networking hardware and VPN routers. Secure your entire home or office with our pre-configured open-source solutions.",
    logo: "/assets/privaterouter-new.png",
    categories: ["💻 Electronics", "🛡️ VPN & Privacy", "⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://privaterouter.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "76",
    name: "IVPN",
    description: "Transparent, privacy-focused VPN service. We don't log your activity and we don't track your identity. Pure privacy without compromise.",
    logo: "/assets/ivpn-new.png",
    categories: ["🛡️ VPN & Privacy", "⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.ivpn.net/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "77",
    name: "Hyke & Byke",
    description: "High-performance outdoor gear for backpackers and hikers. Professional quality sleeping bags, tents, and accessories at direct-to-consumer prices.",
    logo: "/assets/hyke-byke-new.png",
    categories: ["⚽ Sports", "✨ Lifestyle"],
    shippingCountries: ["🇺🇸 USA", "🌍 Worldwide"],
    website: "https://www.hykeandbyke.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "78",
    name: "Kerwell",
    description: "Curated selection of premium CBD and hemp wellness products. Supporting a healthy and balanced lifestyle through high-quality natural extracts.",
    logo: "/assets/kerwell-new.png",
    categories: ["💄 Health & Beauty", "🧘 Wellness", "✨ Lifestyle"],
    shippingCountries: ["🇺🇸 USA"],
    website: "https://kerwell.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "79",
    name: "Sticky",
    description: "Unique Bitcoin-themed stickers and stationary for the sovereign individual. Express your cypherpunk values with our custom artisanal designs.",
    logo: "/assets/sticky-new.png",
    categories: ["🎨 Art", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://getsticky.shop/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "80",
    name: "Samen Maier",
    description: "Organic seeds for vegetable and flower gardens. Promoting sustainable gardening and food sovereignty through high-quality non-GMO seeds.",
    logo: "/assets/samen-maier-new.png",
    categories: ["✨ Lifestyle"],
    shippingCountries: ["🇪🇺 Europe"],
    website: "https://www.samen-maier.at/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "81",
    name: "Smith Pastures",
    description: "Pasture-raised meats from a family farm dedicated to regenerative agriculture. High-quality beef, pork, and poultry delivered direct to your door.",
    logo: "/assets/smith-pastures-v2.png",
    categories: ["🍴 Food & Drink", "✨ Lifestyle"],
    shippingCountries: ["🇺🇸 USA"],
    website: "https://smithpastures.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "82",
    name: "SKOON.",
    description: "High-performance natural skincare from South Africa. Combining traditional botanicals with modern science for effective, ethical beauty solutions.",
    logo: "/assets/skoon-new.png",
    categories: ["💄 Health & Beauty", "🧘 Wellness", "✨ Lifestyle"],
    shippingCountries: ["🇿🇦 South Africa", "🌍 Worldwide"],
    website: "https://www.skoon-skin.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "83",
    name: "Mei Leaf",
    description: "Discover the world's most authentic and flavorful teas. We source directly from artisanal growers to bring you the pinnacle of tea culture.",
    logo: "/assets/mei-leaf-new.png",
    categories: ["🍴 Food & Drink", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://meileaf.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "84",
    name: "MissPrint",
    description: "British design studio creating unique contemporary wallpapers and fabrics. Inspired by nature and a passion for mid-century modern aesthetics.",
    logo: "/assets/missprint-v2.png",
    categories: ["🎨 Art", "✨ Lifestyle"],
    shippingCountries: ["🇬🇧 UK", "🌍 Worldwide"],
    website: "https://www.missprint.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "85",
    name: "Izindlovu",
    description: "Supporting elephant conservation through high-quality artisanal goods. Every purchase helps protect wildlife and preserve their natural habitats.",
    logo: "/assets/izindlovu-logo.png",
    categories: ["❤️ Charity", "🎨 Art", "✨ Lifestyle"],
    shippingCountries: ["🇪🇺 Europe", "🌍 Worldwide"],
    website: "https://www.izindlovu.org/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "86",
    name: "Sole",
    description: "Sustainable footwear and orthopedic insoles designed for comfort and performance. High-quality materials and innovative design for your active lifestyle.",
    logo: "/assets/sole-logo-new.png",
    categories: ["👗 Fashion", "💄 Health & Beauty", "✨ Lifestyle"],
    shippingCountries: ["🇺🇸 USA", "🇨🇦 Canada", "🌍 Worldwide"],
    website: "https://yoursole.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "87",
    name: "FuelingYou",
    description: "Performance nutrition and wellness coaching for peak physical and mental clarity. Personalized plans and high-quality supplements for your health journey.",
    logo: "/assets/fuelingyou-logo-new.png",
    categories: ["💄 Health & Beauty", "🧘 Wellness", "✨ Lifestyle"],
    shippingCountries: ["🇺🇸 USA"],
    website: "https://fuelingyou.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "88",
    name: "Root & Branch",
    description: "Specialty coffee roasters dedicated to transparency and quality. Discover exceptional beans sourced through direct relationships with farmers.",
    logo: "/assets/root-and-branch-new.png",
    categories: ["🍴 Food & Drink", "✨ Lifestyle"],
    shippingCountries: ["🇬🇧 UK", "🌍 Worldwide"],
    website: "https://rootandbranchcoffee.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "89",
    name: "Heatbit",
    description: "The world's first heater that mines Bitcoin. Efficient, quiet, and beautiful heating that earns you money while you sleep.",
    logo: "/assets/heatbit-new.png",
    categories: ["💻 Electronics", "⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://heatbit.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "90",
    name: "NoGood Studio",
    description: "Creative design studio specializing in brand identity and digital experiences. Helping sovereign projects stand out with bold and artisanal design.",
    logo: "/assets/nogood-new.png",
    categories: ["🎨 Art", "⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://nogood.studio/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "91",
    name: "DeGoogled",
    description: "Privacy-focused smartphones and open-source operating systems. Take back control of your data with our pre-configured privacy hardware.",
    logo: "/assets/degoogled-new.png",
    categories: ["💻 Electronics", "🛡️ VPN & Privacy", "⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://degoogled.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "92",
    name: "Crave",
    description: "High-quality, artisan-crafted cookies and sweets delivered to your door. Indulge in our unique flavors and traditional favorites made with the finest ingredients.",
    logo: "/assets/crave-new.png",
    categories: ["🍴 Food & Drink", "🍬 Sweets", "✨ Lifestyle"],
    shippingCountries: ["🇺🇸 USA"],
    website: "https://cravecookies.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "93",
    name: "MMOGA",
    description: "One of the first gaming marketplaces to accept Bitcoin. Buy games, game cards, and virtual goods with ease and security.",
    logo: "/assets/mmoga-new.png",
    categories: ["🎬 Entertainment", "⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.mmoga.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "CoinGate",
    reviews: []
  },
  {
    id: "94",
    name: "Human Trafficking Institute",
    description: "Non-profit organization dedicated to stopping human traffickers. Supporting enforcement and justice systems to end modern slavery.",
    logo: "/assets/hti-new.png",
    categories: ["❤️ Charity"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.traffickinginstitute.org/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "95",
    name: "Uzi Shop",
    description: "Sovereign street wear and artisanal goods. High-quality apparel and accessories designed for those who value freedom and individual expression.",
    logo: "/assets/uzishop-new.png",
    categories: ["👗 Fashion", "✨ Lifestyle", "🎨 Art"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://uzishop.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "96",
    name: "Le Cyclo Sportif",
    description: "Specialist cycling apparel and accessories for the modern rider. Premium gear designed for performance, comfort, and style on the road.",
    logo: "/assets/lecyclosportif-new.png",
    categories: ["⚽ Sports", "👗 Fashion", "✨ Lifestyle"],
    shippingCountries: ["🇦🇺 Australia", "🌍 Worldwide"],
    website: "https://lecyclosportif.com.au/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "97",
    name: "Hill Helicopters",
    description: "Reinventing the personal helicopter with the revolutionary Hill HX50. Precision engineering and artisanal craftsmanship for the ultimate flight experience.",
    logo: "/assets/hillhelicopters-new.png",
    categories: ["🚗 Auto", "⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.hillhelicopters.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "98",
    name: "Alternative Airlines",
    description: "Search and book flights with over 600 airlines and pay with Bitcoin. Discover a more flexible way to travel the world.",
    logo: "/assets/alternativeairlines-v2.png",
    categories: ["✈️ Travel"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.alternativeairlines.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "CoinGate",
    reviews: []
  },
  {
    id: "99",
    name: "Brazilian Botanicals",
    description: "Authentic, high-quality herbal extracts and traditional remedies from the Amazon rainforest. Supporting sustainable practices and tribal knowledge.",
    logo: "/assets/brazilianbotanicals-v2.png",
    categories: ["💄 Health & Beauty", "🧘 Wellness", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.brazilianbotanicals.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "CoinGate",
    reviews: []
  },
  {
    id: "100",
    name: "CyberPiggy",
    description: "Unique Bitcoin-themed piggy banks and physical goods. Artisan-crafted items that help the next generation learn about sound money and saving.",
    logo: "/assets/cyberpiggy-v2.png",
    categories: ["🎨 Art", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://cyberpiggy.io/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "101",
    name: "NordVPN",
    description: "Leading VPN provider offering high-speed, secure, and private internet access. Protect your digital footprint with our advanced security features.",
    logo: "/assets/nordvpn-v2.png",
    categories: ["🛡️ VPN & Privacy", "⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://nordvpn.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "CoinGate",
    reviews: []
  },
  {
    id: "102",
    name: "GameRoom",
    description: "South Africa's premier gaming store. Shop the latest consoles, games, and accessories with Bitcoin for a seamless gaming experience.",
    logo: "/assets/gameroom-v2.png",
    categories: ["🎬 Entertainment", "💻 Electronics", "⚙️ Tech"],
    shippingCountries: ["🇿🇦 South Africa"],
    website: "https://gameroom.co.za/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "103",
    name: "Hotelgift",
    description: "The ultimate hotel gift card, redeemable for over 550,000 hotels worldwide. Give the gift of travel and pay with Bitcoin.",
    logo: "/assets/hotelgift-v2.png",
    categories: ["✈️ Travel", "🎁 Gift Cards"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.hotelgift.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "CoinGate",
    reviews: []
  },
  {
    id: "104",
    name: "ReachTags",
    description: "Digital business cards and smart networking solutions. High-quality NFC-enabled products that help you share your identity instantly.",
    logo: "/assets/reachtags-v2.png",
    categories: ["⚙️ Tech", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://reachtags.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "105",
    name: "Surfshark",
    description: "Award-winning VPN service that prioritizes your online privacy. Secure your data on unlimited devices with our easy-to-use platform.",
    logo: "/assets/surfshark-v2.png",
    categories: ["🛡️ VPN & Privacy", "⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://surfshark.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "CoinGate",
    reviews: []
  },
  {
    id: "106",
    name: "Vintage Guitar World",
    description: "Curated selection of rare and exceptional vintage guitars. Expert appraisal and sales for collectors and professional musicians.",
    logo: "/assets/vintage-guitar-v2.png",
    categories: ["🎵 Music", "🎨 Art", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.vintage-guitar-world.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "107",
    name: "Wayland Games",
    description: "Europe's largest independent retailer of tabletop games, miniatures, and wargaming supplies. Everything you need for your gaming hobby.",
    logo: "/assets/wayland-games-v2.png",
    categories: ["🎬 Entertainment", "✨ Lifestyle"],
    shippingCountries: ["🇪🇺 Europe", "🌍 Worldwide"],
    website: "https://www.waylandgames.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "CoinGate",
    reviews: []
  },
  {
    id: "108",
    name: "ZenMarket",
    description: "Your Japanese proxy shopping service. Buy anything from Japan and have it shipped to your door, paying with Bitcoin for ultimate convenience.",
    logo: "/assets/zenmarket-v2.png",
    categories: ["✈️ Travel", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://zenmarket.jp/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "CoinGate",
    reviews: []
  },
  {
    id: "109",
    name: "Zumub",
    description: "Leading European destination for sports nutrition, supplements, and healthy food. High-quality products to support your fitness and wellness goals.",
    logo: "/assets/zumub-v2.png",
    categories: ["💄 Health & Beauty", "🧘 Wellness", "🍴 Food & Drink"],
    shippingCountries: ["🇪🇺 Europe", "🌍 Worldwide"],
    website: "https://www.zumub.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "CoinGate",
    reviews: []
  },
  {
    id: "110",
    name: "Gift Off",
    description: "Buy gift cards for hundreds of retailers worldwide with Bitcoin. Gift Off makes it easy to live on crypto by offering instant delivery of digital gift cards for your favorite brands.",
    logo: "/assets/giftoff-v2.png",
    categories: ["🎁 Gift Cards", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://giftoff.com",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "CoinGate",
    reviews: []
  },
  {
    id: "111",
    name: "Waking Herbs",
    description: "Your source for high-quality ethnobotanicals and traditional herbal remedies. Dedicated to preserving ancient knowledge and providing ethically sourced herbs from around the world.",
    logo: "/assets/waking-herbs-v2.png",
    categories: ["💄 Health & Beauty", "🧘 Wellness", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.wakingherbs.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "CoinGate",
    reviews: []
  },
  {
    id: "112",
    name: "Freedom of the Press",
    description: "Protecting, defending, and empowering public-interest journalism in the 21st century. Supporting whistleblowers, journalists, and newsrooms through technology and advocacy.",
    logo: "/assets/fotp-v2.png",
    categories: ["❤️ Charity", "🛡️ VPN & Privacy"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://freedom.press/",
    lightningSupported: false,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "113",
    name: "Internet Archive",
    description: "A non-profit library of millions of free books, movies, software, music, websites, and more. Building a digital library of Internet sites and other cultural artifacts in digital form.",
    logo: "/assets/archive-v2.png",
    categories: ["❤️ Charity", "📚 Books"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://archive.org/",
    lightningSupported: false,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  }
];
