export interface Review {
  id: string;
  authorNpub: string;
  rating: number;
  comment: string;
  date: string;
}

export interface Merchant {
  id: string;
  name: string;
  description: string;
  logo: string; // Emoji or initial for now
  categories: string[];
  shippingCountries: string[];
  website: string;
  lightningSupported: boolean;
  onchainSupported: boolean;
  paymentProvider?: string;
  reviews: Review[];
  featured?: boolean;
}

export const PAYMENT_PROVIDERS = [
  "BTCPay Server",
  "Zaprite",
  "Strike",
  "OpenNode",
  "IBEX",
  "CoinCorner",
  "BitPay"
];

export const CATEGORIES = [
  "Electronics",
  "Clothing",
  "Services",
  "Food & Drink",
  "Travel",
  "Gift Cards",
  "VPN & Privacy",
  "Hosting",
  "Books",
  "Art",
  "Charity"
];

export const COUNTRIES = [
  "Worldwide",
  "USA",
  "Europe",
  "Canada",
  "UK",
  "Australia",
  "El Salvador"
];

export const MOCK_MERCHANTS: Merchant[] = [
  {
    id: "1",
    name: "BitRefill",
    description: "Buy Gift Cards & Mobile Refills with Bitcoin. Live on crypto.",
    logo: "/assets/bitrefill-logo.png",
    categories: ["Gift Cards", "Services", "Travel"],
    shippingCountries: ["Worldwide"],
    website: "https://bitrefill.com",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    featured: true,
    reviews: [
      { id: "r1", authorNpub: "npub1...xyz", rating: 5, comment: "Works instantly via Lightning!", date: "2024-03-10" },
      { id: "r2", authorNpub: "npub1...abc", rating: 5, comment: "Essential for living on Bitcoin.", date: "2024-02-15" }
    ]
  },
  {
    id: "2",
    name: "SLNT",
    description: "Privacy-first Faraday bags and signal blocking accessories.",
    logo: "/assets/slnt-logo.png",
    categories: ["Services", "Electronics"],
    shippingCountries: ["Worldwide"],
    website: "https://slnt.com",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "Zaprite",
    reviews: [
      { id: "r3", authorNpub: "npub1...def", rating: 5, comment: "High quality signal blocking gear.", date: "2024-01-20" }
    ]
  },
  {
    id: "3",
    name: "Mullvad VPN",
    description: "Mullvad is a VPN service that helps keep your online activity, identity, and location private.",
    logo: "/assets/mullvad-logo.png",
    categories: ["VPN & Privacy", "Services"],
    shippingCountries: ["Worldwide"],
    website: "https://mullvad.net",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "Strike",
    featured: true,
    reviews: [
      { id: "r4", authorNpub: "npub1...ghi", rating: 5, comment: "Best privacy VPN, accepts cash and BTC.", date: "2024-03-01" }
    ]
  },
  {
    id: "4",
    name: "Coinkite",
    description: "Hardware wallets for Bitcoin security. Makers of Coldcard.",
    logo: "/assets/coinkite-logo.png",
    categories: ["Electronics", "Services"],
    shippingCountries: ["Worldwide"],
    website: "https://coinkite.com",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "5",
    name: "Start9",
    description: "Sovereign computing. Run your own personal server.",
    logo: "/assets/start9-logo.png",
    categories: ["Electronics", "Hosting"],
    shippingCountries: ["Worldwide", "USA"],
    website: "https://start9.com",
    lightningSupported: true,
    onchainSupported: true,
    featured: true,
    reviews: []
  },
  {
    id: "6",
    name: "Daylight Computer",
    description: "Building the first computer that feels like paper. The Daylight Tablet.",
    logo: "/assets/daylight-logo.png",
    categories: ["Electronics"],
    shippingCountries: ["Worldwide"],
    website: "https://daylightcomputer.com",
    lightningSupported: false,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "7",
    name: "Tor Project",
    description: "Defending your rights to privacy and freedom online. Help us keep Tor strong.",
    logo: "/assets/tor-logo-new.png",
    categories: ["Services", "Charity", "VPN & Privacy"],
    shippingCountries: ["Worldwide"],
    website: "https://torproject.org",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "8",
    name: "Namecheap",
    description: "Register domains and buy web hosting with Bitcoin. Privacy-focused domain registrar.",
    logo: "/assets/namecheap-logo.png",
    categories: ["Services", "Hosting"],
    shippingCountries: ["Worldwide"],
    website: "https://namecheap.com",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "9",
    name: "Human Rights Foundation",
    description: "Supporting civil society in closed societies and uniting people in the common cause of human rights.",
    logo: "/assets/hrf-logo.png",
    categories: ["Services", "Charity"],
    shippingCountries: ["Worldwide"],
    website: "https://hrf.org",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "10",
    name: "CheapAir",
    description: "Book flights and hotels with Bitcoin. One of the first travel sites to accept BTC.",
    logo: "/assets/cheapair-logo.png",
    categories: ["Services", "Travel"],
    shippingCountries: ["Worldwide"],
    website: "https://cheapair.com",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "11",
    name: "Travala",
    description: "Book 3,000,000+ travel products worldwide with Bitcoin and other cryptocurrencies.",
    logo: "/assets/travala-logo-new.png",
    categories: ["Services", "Travel"],
    shippingCountries: ["Worldwide"],
    website: "https://travala.com",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "12",
    name: "G2A",
    description: "The world's largest marketplace for digital entertainment. Buy games, gift cards, and software with Bitcoin.",
    logo: "/assets/g2a-logo-new.png",
    categories: ["Services", "Gift Cards"],
    shippingCountries: ["Worldwide"],
    website: "https://g2a.com",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "13",
    name: "Obscura",
    description: "High-performance VPN service built for the Bitcoin ecosystem. Privacy without compromise.",
    logo: "/assets/obscura-logo-new.png",
    categories: ["VPN & Privacy", "Services"],
    shippingCountries: ["Worldwide"],
    website: "https://obscuravpn.com",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "14",
    name: "Silent.link",
    description: "Anonymously purchase eSIMs with Bitcoin. Privacy-first mobile data and SMS services.",
    logo: "/assets/silent-link-logo-new.png",
    categories: ["Services", "VPN & Privacy"],
    shippingCountries: ["Worldwide"],
    website: "https://silent.link",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "15",
    name: "Great Ghee",
    description: "Handcrafted, small-batch ghee made from grass-fed butter. High-quality clarified butter for healthy cooking.",
    logo: "/assets/great-ghee-clean.png",
    categories: ["Food & Drink"],
    shippingCountries: ["USA"],
    website: "https://greatghee.com",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "16",
    name: "Great North Air Ambulance",
    description: "Life-saving charity providing emergency medical care across the North of England. Supporting their operations via Bitcoin donations.",
    logo: "/assets/gnaas-logo-new.png",
    categories: ["Charity", "Health"],
    shippingCountries: ["UK"],
    website: "https://www.greatnorthairambulance.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "17",
    name: "Castle Hill Gin",
    description: "Premium handcrafted gin distilled in the heart of Yorkshire. Traditional methods with modern botanical blends.",
    logo: "/assets/castle-hill-gin-new.png",
    categories: ["Food & Drink", "Alcohol"],
    shippingCountries: ["UK"],
    website: "https://www.castlehillgin.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "18",
    name: "Bonjour Wines",
    description: "Specialist importer of fine French wines and artisanal spirits. Discover a curated selection of exceptional vineyards.",
    logo: "/assets/bonjour-wines-new.png",
    categories: ["Food & Drink", "Alcohol"],
    shippingCountries: ["UK"],
    website: "https://www.bonjourwines.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "19",
    name: "Peony Lane Wine",
    description: "Artisan winery specializing in elegant, floral-noted wines. Experience the unique terroir of our boutique vineyards.",
    logo: "/assets/peony-lane-new.png",
    categories: ["Food & Drink", "Alcohol"],
    shippingCountries: ["USA"],
    website: "https://www.peonylanewine.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "20",
    name: "Yum Yum Tree Fudge",
    description: "Premium handcrafted fudge made with natural ingredients. Discover a vast array of unique and traditional flavors from this artisan confectioner.",
    logo: "/assets/yum-yum-tree-fudge-new.png",
    categories: ["Food & Drink", "Sweets"],
    shippingCountries: ["UK", "Worldwide"],
    website: "https://www.yumyumtreefudge.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "21",
    name: "Tea and Tonic",
    description: "British luxury skincare and wellness brand using high-performance adaptogens and sustainable ingredients to support body and mind.",
    logo: "/assets/tea-and-tonic-new.png",
    categories: ["Health & Beauty", "Wellness"],
    shippingCountries: ["UK", "Worldwide"],
    website: "https://www.teaandtonic.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "22",
    name: "AroTags",
    description: "Premium wood air fresheners for your car. Long-lasting, artisan-crafted scents using high-quality essential oils.",
    logo: "/assets/arotags-new.png",
    categories: ["Auto", "Lifestyle"],
    shippingCountries: ["USA", "Worldwide"],
    website: "https://www.arotags.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "23",
    name: "Spitting Feathers",
    description: "Award-winning independent brewery and pub. Crafting exceptional real ales and craft beers with a focus on quality and tradition.",
    logo: "/assets/spitting-feathers-fox.png",
    categories: ["Food & Drink", "Alcohol"],
    shippingCountries: ["UK"],
    website: "https://spittingfeathers.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "24",
    name: "Mushmore Supplements",
    description: "Premium mushroom supplements crafted for optimal wellness. Harnessing the power of functional fungi for clarity, focus, and vitality.",
    logo: "/assets/mushmore-logo.png",
    categories: ["Health & Beauty", "Wellness"],
    shippingCountries: ["USA", "Worldwide"],
    website: "https://www.mushmoresupplements.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "25",
    name: "Hummingbird Amsterdam",
    description: "Specialty coffee bar and store in the heart of Amsterdam. Discover a curated selection of coffee beans and brewing equipment.",
    logo: "/assets/hummingbird-logo.png",
    categories: ["Food & Drink", "Lifestyle"],
    shippingCountries: ["Netherlands", "Europe"],
    website: "https://www.hummingbird.amsterdam/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "26",
    name: "Planet Express",
    description: "Your premier package forwarding and shipping partner. Ship from the USA to anywhere in the world with ease and reliability.",
    logo: "/assets/planet-express-logo.png",
    categories: ["Services", "Lifestyle"],
    shippingCountries: ["USA", "Worldwide"],
    website: "https://planetexpress.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "27",
    name: "Farfetch",
    description: "The global destination for modern luxury. Shop the world's best designers and boutiques for clothing, shoes, and accessories.",
    logo: "/assets/farfetch-logo.png",
    categories: ["Fashion", "Lifestyle"],
    shippingCountries: ["Worldwide"],
    website: "https://www.farfetch.com/",
    lightningSupported: false,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "28",
    name: "Bramleigh Farm",
    description: "Family-run regenerative farm in the KZN Midlands. Premium pasture-raised chicken, eggs, pork, and grass-fed beef delivered direct to your door.",
    logo: "/assets/bramleigh-logo.png",
    categories: ["Food & Drink", "Wellness"],
    shippingCountries: ["South Africa"],
    website: "https://www.bramleigh.co.za/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "29",
    name: "Oshi Good",
    description: "Specialty coffee and cafe goods. Discover premium coffee beans and accessories for the perfect home brewing experience.",
    logo: "/assets/oshi-new.png",
    categories: ["Food & Drink", "Lifestyle"],
    shippingCountries: ["USA"],
    website: "https://www.oshigood.us/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "30",
    name: "Palingshop",
    description: "Traditional Dutch smoked eel and premium seafood delicacies delivered fresh from Volendam. Experience authentic Dutch flavors.",
    logo: "/assets/palingshop-logo.png",
    categories: ["Food & Drink"],
    shippingCountries: ["Netherlands", "Europe"],
    website: "https://www.palingshop.nl/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "31",
    name: "Ticketpro",
    description: "South Africa's leading ticketing provider for sports, concerts, and events. Book your next experience with Bitcoin.",
    logo: "/assets/ticketpro-logo.png",
    categories: ["Services", "Entertainment"],
    shippingCountries: ["South Africa"],
    website: "https://www.ticketpro.co.za/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "32",
    name: "Dynadot",
    description: "Affordable domain registration and hosting services. Manage your digital identity with ease and security.",
    logo: "/assets/dynadot-logo.png",
    categories: ["Services", "Tech"],
    shippingCountries: ["Worldwide"],
    website: "https://www.dynadot.com/",
    lightningSupported: false,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "33",
    name: "Soapminer",
    description: "Handcrafted natural soaps for Bitcoiners. High-quality ingredients and unique designs that celebrate the Bitcoin lifestyle.",
    logo: "/assets/soapminer-logo.png",
    categories: ["Health & Beauty", "Lifestyle"],
    shippingCountries: ["Worldwide"],
    website: "https://soapminer.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "34",
    name: "MobiMatter",
    description: "The best eSIM marketplace for travelers. Get instant connectivity worldwide with affordable data plans.",
    logo: "/assets/mobimatter-logo.png",
    categories: ["Services", "Travel", "Tech"],
    shippingCountries: ["Worldwide"],
    website: "https://mobimatter.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "35",
    name: "The Good Beans",
    description: "Ethically sourced, freshly roasted specialty coffee. Discover a wide variety of unique blends and single-origin beans.",
    logo: "/assets/thegoodbeans-logo.png",
    categories: ["Food & Drink", "Lifestyle"],
    shippingCountries: ["Worldwide"],
    website: "https://thegoodbeans.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "36",
    name: "Pumphreys Coffee",
    description: "Multi-award winning coffee roasters based in the North East of England since 1750. Specialists in finest quality coffee and tea.",
    logo: "/assets/pumphreys-logo.png",
    categories: ["Food & Drink", "Lifestyle"],
    shippingCountries: ["UK", "Worldwide"],
    website: "https://pumphreys-coffee.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "38",
    name: "Epic Deals",
    description: "South Africa's leading platform for pre-owned and new tech. Shop smartphones, tablets, and more with Bitcoin.",
    logo: "/assets/epicdeals-logo.png",
    categories: ["Electronics", "Tech"],
    shippingCountries: ["South Africa"],
    website: "https://epicdeals.co.za/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "39",
    name: "Farmer Bill's Provisions",
    description: "Premium, craft beef jerky and meat snacks. Ethically sourced and packed with flavor, delivered to your door.",
    logo: "/assets/farmerbills-logo.png",
    categories: ["Food & Drink", "Lifestyle"],
    shippingCountries: ["USA"],
    website: "https://farmerbillsprovisions.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "40",
    name: "Acme Acres",
    description: "Pasture-raised heritage pork and poultry from a family-owned farm. Focused on ethical farming and sustainable practices.",
    logo: "/assets/acmeacres-logo.png",
    categories: ["Food & Drink", "Lifestyle"],
    shippingCountries: ["USA"],
    website: "https://acmeacres.us/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "41",
    name: "Chroma",
    description: "Chroma is dedicated to staying on the cutting edge of light therapy. Your support pushes forward devices designed by engineers who care deeply about health.",
    logo: "/assets/chroma-new.png",
    categories: ["Services", "Tech"],
    shippingCountries: ["Worldwide"],
    website: "https://getchroma.co/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "42",
    name: "Kawa",
    description: "Specialty coffee roastery offering unique and flavorful beans. Experience the art of Japanese-inspired coffee roasting.",
    logo: "/assets/kawa-new.png",
    categories: ["Food & Drink", "Lifestyle"],
    shippingCountries: ["Worldwide"],
    website: "https://www.u2kawa.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "43",
    name: "Kijicha",
    description: "Authentic Japanese tea and premium matcha sourced directly from growers. Experience the tradition and serenity of high-quality tea.",
    logo: "/assets/kijicha-new.png",
    categories: ["Food & Drink", "Lifestyle"],
    shippingCountries: ["Worldwide"],
    website: "https://kijicha.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "44",
    name: "Leeds Gin",
    description: "Premium gin hand crafted in small batches in the heart of Yorkshire. Traditional botanicals steeped with juniper, coriander, ginger and orange.",
    logo: "https://www.leedsgin.com/wp-content/uploads/elementor/thumbs/cropped-Favicon-v2-01-plyh4y2k69gla83ozhwxsz3smo2eeooufuj8remsgw.png",
    categories: ["Food & Drink", "Alcohol"],
    shippingCountries: ["UK"],
    website: "https://www.leedsgin.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "45",
    name: "ASF Tutoring",
    description: "Online Maths tutor specialising in 1-1 and small group tuition. Empowering young people to have confidence in their mathematical ability.",
    logo: "/assets/asf-tutoring-new.png",
    categories: ["Services", "Tech"],
    shippingCountries: ["Worldwide"],
    website: "https://www.asftutoring.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "46",
    name: "The Suffolk Tutor",
    description: "Personalised primary school tutoring and specialist SEND support. Qualified teacher offering one-to-one and group sessions in Maths, English, and Science.",
    logo: "https://static.wixstatic.com/media/e7f737_461ad44966af488b8bdfee9c8146a001~mv2.png/v1/fill/w_385,h_465,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/%40thesuffolktutor.png",
    categories: ["Services", "Tech"],
    shippingCountries: ["Worldwide", "UK"],
    website: "https://www.thesuffolktutor.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "47",
    name: "Jimble's Jumble",
    description: "Homemade preserves created in Northamptonshire from homegrown, wild foraged and food rescued ingredients. Small-batch jams, chutneys, and marmalades.",
    logo: "https://jimblesjumble.odoo.com/web/image/3369-f7e687f9/3-DSC_0022.webp",
    categories: ["Food & Drink", "Lifestyle"],
    shippingCountries: ["UK"],
    website: "https://jimblesjumble.odoo.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "48",
    name: "Hempful",
    description: "Premium European CBD and hemp products. High-potency, full-spectrum CBD oils, beverages, and skincare grown in the perfect climate for maximum potency.",
    logo: "/assets/hempful-new.png",
    categories: ["Food & Drink", "Wellness", "Health & Beauty"],
    shippingCountries: ["Worldwide", "UK", "Europe"],
    website: "https://hempful.eu/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "49",
    name: "Highland Fayre",
    description: "Scotland's No. 1 specialist hamper company. Luxury food and wine hampers, gift baskets, and corporate gifts delivered throughout the UK.",
    logo: "/assets/highland-fayre-new.png",
    categories: ["Food & Drink", "Alcohol", "Lifestyle"],
    shippingCountries: ["UK"],
    website: "https://www.highlandfayre.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "50",
    name: "Golden Tallow",
    description: "Luxurious skincare powered by pure Wagyu tallow. Nutrient-rich, artisanal formulations designed to restore and elevate your natural glow.",
    logo: "/assets/golden-tallow-logo.png",
    categories: ["Health & Beauty", "Wellness", "Lifestyle"],
    shippingCountries: ["Worldwide"],
    website: "https://goldentallow.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "51",
    name: "Mister Padel",
    description: "Italy's premier padel equipment specialist. Discover a wide selection of professional rackets, apparel, and accessories from leading brands like Nox, Bullpadel, and Adidas.",
    logo: "/assets/mister-padel-icon.png",
    categories: ["Sports", "Clothing", "Lifestyle"],
    shippingCountries: ["Italy", "Europe"],
    website: "https://www.misterpadel.it/",
    lightningSupported: false,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "52",
    name: "Lincoln Kiln Dried Logs",
    description: "Premium kiln-dried hardwood logs delivered throughout Lincoln and the surrounding areas. Sustainably sourced, high-quality firewood for efficient and clean burning.",
    logo: "/assets/lincoln-logs-delivery-v2.png",
    categories: ["Lifestyle", "Services"],
    shippingCountries: ["UK"],
    website: "https://www.lincolnkilndriedlogs.co.uk/",
    lightningSupported: false,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "53",
    name: "Essatoshi",
    description: "Experience the essence of Satoshi. Curated Bitcoin-themed lifestyle goods and essentials designed for the modern bitcoiner.",
    logo: "/assets/essatoshi-logo.png",
    categories: ["Lifestyle", "Clothing", "Art"],
    shippingCountries: ["Worldwide"],
    website: "https://essatoshi.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "54",
    name: "Cheerings",
    description: "Exceptional mood-enhancing earrings on a mission to spread cheer. Handpicked, unique designs that are 'Lobe Load' tested for featherlight comfort.",
    logo: "/assets/cheerings-logo-new.png",
    categories: ["Fashion", "Lifestyle", "Gift Cards"],
    shippingCountries: ["UK", "Worldwide"],
    website: "https://cheerings.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "55",
    name: "Jonathan Hill Luthier",
    description: "Historical and modern stringed instrument maker. Specialist in Viola d'amore, Lira da braccio, and bespoke historical instruments crafted with traditional methods.",
    logo: "/assets/jonathan-hill-logo-new.png",
    categories: ["Art", "Music", "Services"],
    shippingCountries: ["UK", "Worldwide"],
    website: "https://www.jonathanhill-luthier.com/",
    lightningSupported: false,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "56",
    name: "Select Automotive",
    description: "Premium quality automotive parts for the vehicle aftermarket sector. UK supplier of window regulators, door locks, and more with expert support.",
    logo: "/assets/select-automotive-logo-new.png",
    categories: ["Auto", "Services"],
    shippingCountries: ["UK"],
    website: "https://www.selectautomotive.co.uk/",
    lightningSupported: false,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "57",
    name: "CandyJets",
    description: "Private jet charter services for business and leisure travel. Experience seamless travel with a bespoke 'Candy Concierge' service for a sweet and stress-free journey.",
    logo: "/assets/candyjets-logo-gold-circle.png",
    categories: ["Travel", "Services"],
    shippingCountries: ["UK", "Europe"],
    website: "https://candyjets.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "58",
    name: "Maple AI",
    description: "Private AI chat with end-to-end encryption. Powered by OpenSecret, Maple ensures your conversations stay yours with cryptographic proof of privacy.",
    logo: "/assets/maple-ai-logo-new.png",
    categories: ["Tech", "VPN & Privacy", "Services"],
    shippingCountries: ["Worldwide"],
    website: "https://trymaple.ai/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "59",
    name: "PayPerQ",
    description: "Get instant access to hundreds of powerful AI models with no subscriptions. Pay only for what you use with Lightning, Bitcoin, and other privacy-respecting payments.",
    logo: "https://ppq.ai/flame2.png",
    categories: ["Tech", "Services"],
    shippingCountries: ["Worldwide"],
    website: "https://ppq.ai/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "60",
    name: "Crypto Tax Help",
    description: "Leading UK tax and cryptocurrency accountant. Expert advice for Hodlers, Traders, and DAO enthusiasts to simplify crypto taxes and ensure HMRC compliance.",
    logo: "/assets/crypto-tax-help-logo-new.png",
    categories: ["Services", "Tech"],
    shippingCountries: ["UK"],
    website: "https://cryptotaxhelp.co.uk/",
    lightningSupported: false,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "61",
    name: "MtSocks",
    description: "Bitcoin-themed socks that tell a story. High-quality, limited edition socks celebrating the history and culture of Bitcoin. Finite supply, just like the real thing.",
    logo: "/assets/mtsocks-new.png",
    categories: ["Clothing", "Lifestyle"],
    shippingCountries: ["Worldwide"],
    website: "https://mtsocks.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "62",
    name: "TorGuard",
    description: "Secure and private VPN, Proxy, and Email services. Protect your online identity with high-speed, anonymous browsing and advanced encryption.",
    logo: "/assets/torguard-new.png",
    categories: ["VPN & Privacy", "Services"],
    shippingCountries: ["Worldwide"],
    website: "https://torguard.net/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "63",
    name: "Beef Initiative",
    description: "A movement focused on making food more localized, redundant, and secure. Providing market access to ranchers and consumers who value food integrity and regenerative practices.",
    logo: "/assets/beef-initiative-logo.png",
    categories: ["Food & Drink", "Wellness", "Lifestyle"],
    shippingCountries: ["USA"],
    website: "https://beefinitiative.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "64",
    name: "Spy Equipment UK",
    description: "High-quality, reliable surveillance and security solutions. Specialists in spy cameras, listening devices, and tracking equipment for professional and personal use.",
    logo: "/assets/spy-equipment-new.png",
    categories: ["Tech", "Services"],
    shippingCountries: ["UK", "Worldwide"],
    website: "https://www.spyequipmentuk.co.uk/",
    lightningSupported: false,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "65",
    name: "Bees & Trees",
    description: "Authentic, high-activity Mānuka honey from New Zealand's pristine forests. Sustainably sourced and independently tested for potency and purity.",
    logo: "/assets/bees-and-trees-logo.png",
    categories: ["Food & Drink", "Wellness", "Health & Beauty"],
    shippingCountries: ["USA", "Worldwide"],
    website: "https://www.beesandtrees.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "66",
    name: "KaffeBox",
    description: "Subscription service for Scandinavian specialty coffee. Freshly roasted beans from the best Nordic micro-roasteries delivered monthly.",
    logo: "/assets/kaffebox-logo.png",
    categories: ["Food & Drink", "Lifestyle"],
    shippingCountries: ["Norway", "Worldwide"],
    website: "https://www.kaffebox.no/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "67",
    name: "Bloom Audio",
    description: "Premium headphones and personal audio equipment. Expertly curated selection of high-fidelity audio gear for the discerning listener.",
    logo: "/assets/bloom-audio-logo.png",
    categories: ["Electronics", "Services"],
    shippingCountries: ["USA", "Worldwide"],
    website: "https://bloomaudio.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "68",
    name: "La Industria Handmade",
    description: "Artisan handmade tobacco pouches, belt bags, and sustainable accessories. Crafted with passion using organic cotton and recycled materials.",
    logo: "/assets/la-industria-logo.png",
    categories: ["Clothing", "Lifestyle"],
    shippingCountries: ["Europe", "Worldwide"],
    website: "https://laindustriahandmade.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "69",
    name: "Campo Apícola",
    description: "Conscious beekeeping from Santander, Colombia. Pure honey, pollen, propolis, and beeswax candles crafted with love and respect for nature.",
    logo: "https://www.campoapicola.com/wp-content/uploads/2023/10/logo-apicola.png",
    categories: ["Food & Drink", "Lifestyle"],
    shippingCountries: ["Worldwide"],
    website: "https://www.campoapicola.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "70",
    name: "Elephant Chateau",
    description: "Ethically sourced, single-estate Ceylon teas and gourmet spices. Discover the world's most flavorful selection of aromatic leafy teas and fresh cinnamon.",
    logo: "https://elephantchateau.com/images/logo-crest2.png",
    categories: ["Food & Drink", "Lifestyle"],
    shippingCountries: ["Worldwide"],
    website: "https://elephantchateau.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "71",
    name: "Árbol de Maple",
    description: "Handcrafted wooden furniture and educational toys for children. High-quality designs for bedrooms, play areas, and early childhood centers in Ecuador.",
    logo: "/assets/arbol-de-maple-new.png",
    categories: ["Clothing", "Lifestyle"],
    shippingCountries: ["Worldwide"],
    website: "https://www.arboldemaple.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "72",
    name: "Consumer Choice Center",
    description: "A global consumer advocacy group fighting for lifestyle freedom, innovation, and consumer choice across the globe. We empower your voice in the halls of power.",
    logo: "/assets/ccc-logo-new.png",
    categories: ["Services", "Charity"],
    shippingCountries: ["Worldwide"],
    website: "https://consumerchoicecenter.org/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "73",
    name: "PikaSim",
    description: "Private travel eSIMs with instant setup in 190+ countries. No signup, no account, and no KYC required. Pay with Bitcoin or Lightning.",
    logo: "/assets/pikasim-new.png",
    categories: ["Travel", "Services", "VPN & Privacy"],
    shippingCountries: ["Worldwide"],
    website: "https://pikasim.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "74",
    name: "Mad Gringo Hot Sauce",
    description: "Premium handcrafted Canadian hot sauces. From mild to wild, experience bold flavors and fiery heat with our artisanal small-batch sauces.",
    logo: "/assets/mad-gringo-new.png",
    categories: ["Food & Drink", "Lifestyle"],
    shippingCountries: ["Canada", "USA", "Worldwide"],
    website: "https://canadianhotsauce.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "75",
    name: "PrivateRouter",
    description: "Secure your home or office network with pre-configured VPN routers. Privacy-first hardware supporting Wireguard, OpenVPN, and anonymous hosting.",
    logo: "/assets/privaterouter-new.png",
    categories: ["Electronics", "Services", "VPN & Privacy"],
    shippingCountries: ["Worldwide"],
    website: "https://privaterouter.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "76",
    name: "IVPN",
    description: "Privacy-first VPN service with no logs, no customer data collection, and independent security audits. Accept cash, Monero, and Bitcoin for ultimate anonymity.",
    logo: "/assets/ivpn-new.png",
    categories: ["VPN & Privacy", "Services"],
    shippingCountries: ["Worldwide"],
    website: "https://www.ivpn.net/en/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "77",
    name: "Hyke & Byke",
    description: "Premium backpacking and outdoor gear. High-quality sleeping bags, tents, and pads designed for performance and value. Built for the modern adventurer.",
    logo: "/assets/hyke-byke-new.png",
    categories: ["Clothing", "Lifestyle"],
    shippingCountries: ["USA", "Worldwide"],
    website: "https://www.hykeandbyke.com/",
    lightningSupported: false,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "78",
    name: "Kerwell",
    description: "Premium CBD and wellness products focused on stress relief, better sleep, and pain management. Lab-tested extracts backed by science and transparency.",
    logo: "/assets/kerwell-new.png",
    categories: ["Health & Beauty", "Wellness", "Lifestyle"],
    shippingCountries: ["USA"],
    website: "https://kerwellness.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "79",
    name: "Sticky",
    description: "Singapore's first handmade rock candy store. Artisan candy makers crafting vibrant, custom-made sweets and lollipops entirely by hand.",
    logo: "/assets/sticky-new.png",
    categories: ["Food & Drink", "Sweets", "Lifestyle"],
    shippingCountries: ["Singapore", "Worldwide"],
    website: "https://sticky.com.sg/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "80",
    name: "Samen Maier",
    description: "Organic seeds, flower bulbs, and gardening supplies. High-quality ecological products for sustainable gardening and biodiversity.",
    logo: "/assets/samen-maier-new.png",
    categories: ["Lifestyle", "Wellness"],
    shippingCountries: ["Europe", "Austria", "Germany"],
    website: "https://www.samen-maier.at/shop",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "81",
    name: "Smith Pastures",
    description: "Family-owned farm specializing in pasture-raised heritage pork, poultry, and grass-fed meats. Focused on regenerative agriculture and providing nutrient-dense food.",
    logo: "https://smithpastures.com/wp-content/uploads/2023/03/shadow-logo-1.png",
    categories: ["Food & Drink", "Lifestyle"],
    shippingCountries: ["USA"],
    website: "https://smithpastures.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "82",
    name: "SKOON.",
    description: "Premium South African skincare brand combining science and nature. Clean, non-toxic beauty products formulated with high-performance ingredients for radiant skin.",
    logo: "/assets/skoon-new.png",
    categories: ["Health & Beauty", "Wellness"],
    shippingCountries: ["South Africa", "Worldwide"],
    website: "https://www.skoonskin.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "83",
    name: "Mei Leaf",
    description: "Curators of pinnacle specialty tea and unique teaware. Discover artisan-crafted teas from ancient heirloom cultivars, focusing on deep flavor and traditional methods.",
    logo: "/assets/mei-leaf-new.png",
    categories: ["Food & Drink", "Wellness", "Lifestyle"],
    shippingCountries: ["Worldwide", "UK"],
    website: "https://meileaf.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "84",
    name: "MissPrint",
    description: "Independent British design studio creating beautifully unique, hand-drawn wallpapers, fabrics, and home accessories with a focus on mid-century style and nature.",
    logo: "https://www.missprint.co.uk/img/missprint_logo.svg",
    categories: ["Lifestyle", "Art"],
    shippingCountries: ["UK", "Worldwide"],
    website: "https://www.missprint.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "85",
    name: "Izindlovu",
    description: "Supporting elephant conservation through the sale of artisan-crafted goods and art. A portion of every purchase goes directly to protecting these magnificent creatures and their habitats.",
    logo: "/assets/izindlovu-logo.png",
    categories: ["Charity", "Art", "Lifestyle"],
    shippingCountries: ["Worldwide"],
    website: "https://izindlovu.org/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "86",
    name: "SOLE",
    description: "Premium supportive insoles and footwear designed for comfort and performance. SOLE products are crafted to provide orthopedic support and improve foot health.",
    logo: "/assets/sole-logo-new.png",
    categories: ["Fashion", "Wellness", "Lifestyle"],
    shippingCountries: ["USA", "Canada", "Worldwide"],
    website: "https://yoursole.com/us",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "87",
    name: "Fuelingyou",
    description: "Premium bio-hacking and health optimization supplements and products. Discover a curated selection of high-quality tools to improve your physical and mental performance.",
    logo: "/assets/fuelingyou-logo-new.png",
    categories: ["Health & Beauty", "Wellness", "Lifestyle"],
    shippingCountries: ["Netherlands", "Europe", "Worldwide"],
    website: "https://fuelingyou.nl/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "88",
    name: "Root & Branch",
    description: "Specialty coffee roasters based in Belfast, Northern Ireland. Focusing on ethically sourced, high-quality beans and precision roasting to highlight unique flavor profiles.",
    logo: "/assets/root-and-branch-new.png",
    categories: ["Food & Drink", "Lifestyle"],
    shippingCountries: ["UK", "Ireland", "Worldwide"],
    website: "https://rootandbranch.coffee/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "89",
    name: "Atoms",
    description: "Makers of the most comfortable everyday shoes. Designed in New York, Atoms are known for their cloud-like comfort, antimicrobial copper lining, and perfect fit in quarter sizes.",
    logo: "/assets/atoms-new-logo.png",
    categories: ["Fashion", "Lifestyle", "Wellness"],
    shippingCountries: ["USA", "Worldwide"],
    website: "https://atoms.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "90",
    name: "Heatbit",
    description: "The world's first Bitcoin mining heaters and air purifiers. Heat your home while earning Bitcoin with next-generation smart devices designed in New York.",
    logo: "/assets/heatbit-new.png",
    categories: ["Tech", "Electronics", "Lifestyle"],
    shippingCountries: ["USA", "Canada", "Worldwide"],
    website: "https://heatbit.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "91",
    name: "NoGood Studio",
    description: "Freelance illustrator and design studio inspired by retro tech and fueled by the open-source movement. Amsterdam-based creator of The NoGood Book, limited edition prints, and apparel.",
    logo: "/assets/nogood-new.png",
    categories: ["Art", "Lifestyle", "Fashion"],
    shippingCountries: ["Worldwide", "Netherlands"],
    website: "https://www.nogood.studio/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "92",
    name: "DeGoogled",
    description: "Reclaim your mobile privacy with phones powered by privacy-focused operating systems. De-Googled provides secure, 100% private mobile experiences without intrusive tracking or data mining.",
    logo: "/assets/degoogled-new.png",
    categories: ["Tech", "VPN & Privacy", "Electronics"],
    shippingCountries: ["Worldwide"],
    website: "https://de-googled.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "93",
    name: "Crave",
    description: "The world's leading nicotine toothpick brand. Infused with bold flavors, Crave provides a discreet, smoke-free, and odorless way to enjoy nicotine anywhere, anytime.",
    logo: "/assets/crave-new.png",
    categories: ["Lifestyle", "Wellness"],
    shippingCountries: ["USA", "Worldwide"],
    website: "https://cravepicks.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "94",
    name: "MMOGA",
    description: "One of the first professional mediators of game services on the European market. MMOGA provides a wide range of products for online games, software keys, and gift cards with over 15 years of experience.",
    logo: "/assets/mmoga-new.png",
    categories: ["Entertainment", "Services", "Tech"],
    shippingCountries: ["Europe", "Worldwide"],
    website: "https://www.mmoga.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "95",
    name: "Human Trafficking Institute",
    description: "HTI works to stop traffickers by partnering with law enforcement to decimate trafficking at its source. By stopping traffickers, they free current victims and prevent future exploitation through targeted enforcement strategies.",
    logo: "/assets/hti-square.png",
    categories: ["Services", "Tech"],
    shippingCountries: ["USA", "Worldwide"],
    website: "https://traffickinginstitute.org/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "96",
    name: "Uzi Shop",
    description: "One of Croatia's leading online IT stores, offering a massive range of computer components, peripherals, and gaming equipment. Known for competitive pricing and a specialized selection of high-end hardware.",
    logo: "/assets/uzishop-new.png",
    categories: ["Tech", "Electronics", "Entertainment"],
    shippingCountries: ["Croatia", "Europe"],
    website: "https://www.uzishop.hr/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "97",
    name: "Le Cyclo Sportif",
    description: "Melbourne's premier destination for high-performance cycling. Specializing in road, mountain, and e-bikes, they offer a curated selection of world-class brands and expert mechanical services.",
    logo: "/assets/lecyclosportif-new.png",
    categories: ["Sports & Outdoors", "Lifestyle"],
    shippingCountries: ["Australia"],
    website: "https://www.lecyclosportif.com.au/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "102",
    name: "Hill Helicopters",
    description: "The world's first truly private helicopter. Hill Helicopters is revolutionizing general aviation with the HX50 and HC50, combining luxury, performance, and an innovative ownership model.",
    logo: "/assets/hillhelicopters-v3.png",
    categories: ["Travel", "Tech", "Lifestyle"],
    shippingCountries: ["Worldwide"],
    website: "https://www.hillhelicopters.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "Zaprite",
    reviews: []
  },
  {
    id: "109",
    name: "Alternative Airlines",
    description: "A global flight search and booking site that offers a massive choice of 600+ airlines. Alternative Airlines provides a seamless way to book flights using Bitcoin and other cryptocurrencies.",
    logo: "/assets/alternativeairlines-v2.png",
    categories: ["Travel", "Services"],
    shippingCountries: ["Worldwide"],
    website: "https://www.alternativeairlines.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BitPay",
    reviews: []
  },
  {
    id: "110",
    name: "Brazilian Botanicals",
    description: "Specialists in high-quality traditional Brazilian teas and rare botanicals. Sustainably sourced directly from caring farmers, offering 100% natural, unprocessed ingredients for a unique tea experience.",
    logo: "/assets/brazilianbotanicals-v2.png",
    categories: ["Food & Drink", "Health", "Lifestyle"],
    shippingCountries: ["Worldwide", "USA"],
    website: "https://www.brazilianbotanicals.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    reviews: []
  },
  {
    id: "111",
    name: "CyberPiggy",
    description: "Your destination for high-performance gaming peripherals, custom PCs, and futuristic tech. From VR headsets to ergonomic gaming chairs, CyberPiggy brings the ultimate cyber-experience to your setup.",
    logo: "/assets/cyberpiggy-v2.png",
    categories: ["Tech", "Electronics", "Entertainment"],
    shippingCountries: ["Europe", "Worldwide"],
    website: "https://cyberpiggy.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BitPay",
    reviews: []
  },
  {
    id: "112",
    name: "NordVPN",
    description: "The world's leading VPN provider, offering high-speed encryption, malware protection, and unrestricted internet access. Secure your digital life on all your devices with NordVPN's advanced security features.",
    logo: "/assets/nordvpn-logo.png",
    categories: ["VPN & Privacy", "Services", "Tech"],
    shippingCountries: ["Worldwide"],
    website: "https://nordvpn.com/",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BitPay",
    reviews: []
  }
];
