export interface Review {
  id: string;
  authorNpub: string;
  rating: number;
  comment: string;
  date: string;
}

export interface Merchant {
  id: string;
  name: string;
  description: string;
  logo: string; // Emoji or initial for now
  categories: string[];
  shippingCountries: string[];
  website: string;
  lightningSupported: boolean;
  onchainSupported: boolean;
  paymentProvider?: string;
  reviews: Review[];
  featured?: boolean;
  countryMadeIn?: string;
  countryShippedFrom?: string;
}

export const PAYMENT_PROVIDERS = [
  "BTCPay Server",
  "Zaprite",
  "Strike",
  "OpenNode",
  "IBEX",
  "CoinCorner",
  "CoinGate"
];

export const CATEGORIES = [
  "💻 Electronics",
  "👕 Clothing",
  "🍴 Food & Drink",
  "✈️ Travel",
  "🎁 Gift Cards",
  "🛡️ VPN & Privacy",
  "🌐 Hosting",
  "📚 Books",
  "🎨 Art",
  "❤️ Charity",
  "🏥 Health",
  "👗 Fashion",
  "✨ Lifestyle",
  "💄 Health & Beauty",
  "🧘 Wellness",
  "🚗 Auto",
  "⚽ Sports",
  "🎵 Music",
  "⚙️ Tech",
  "🎬 Entertainment",
  "🍷 Alcohol",
  "🍬 Sweets"
];

export const COUNTRIES = [
  "🌍 Worldwide",
  "🇺🇸 USA",
  "🇪🇺 Europe",
  "🇨🇦 Canada",
  "🇬🇧 UK",
  "🇦🇺 Australia",
  "🇸🇻 El Salvador",
  "🇸🇪 Sweden"
];

export const MOCK_MERCHANTS: Merchant[] = [
  {
    id: "1",
    name: "BitRefill",
    description: "Buy Gift Cards & Mobile Refills with Bitcoin. Live on crypto.",
    logo: "/assets/bitrefill-logo.png",
    categories: ["🎁 Gift Cards", "✈️ Travel"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://bitrefill.com",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "BTCPay Server",
    featured: true,
    reviews: [
      { id: "r1", authorNpub: "npub1...xyz", rating: 5, comment: "Works instantly via Lightning!", date: "2024-03-10" },
      { id: "r2", authorNpub: "npub1...abc", rating: 5, comment: "Essential for living on Bitcoin.", date: "2024-02-15" }
    ]
  },
  {
    id: "2",
    name: "SLNT",
    description: "Privacy-first Faraday bags and signal blocking accessories.",
    logo: "/assets/slnt-logo.png",
    categories: ["💻 Electronics"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://slnt.com",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "Zaprite",
    countryShippedFrom: "USA",
    countryMadeIn: "USA",
    reviews: [
      { id: "r3", authorNpub: "npub1...def", rating: 5, comment: "High quality signal blocking gear.", date: "2024-01-20" }
    ]
  },
  {
    id: "3",
    name: "Mullvad VPN",
    description: "Mullvad is a VPN service that helps keep your online activity, identity, and location private.",
    logo: "/assets/mullvad-logo.png",
    categories: ["🛡️ VPN & Privacy"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://mullvad.net",
    lightningSupported: true,
    onchainSupported: true,
    paymentProvider: "Strike",
    countryShippedFrom: "Sweden",
    countryMadeIn: "Sweden",
    featured: true,
    reviews: [
      { id: "r4", authorNpub: "npub1...ghi", rating: 5, comment: "Best privacy VPN, accepts cash and BTC.", date: "2024-03-01" }
    ]
  },
  {
    id: "4",
    name: "Coinkite",
    description: "Hardware wallets for Bitcoin security. Makers of Coldcard.",
    logo: "/assets/coinkite-logo.png",
    categories: ["💻 Electronics"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://coinkite.com",
    lightningSupported: true,
    onchainSupported: true,
    countryShippedFrom: "Canada",
    countryMadeIn: "Canada",
    reviews: []
  },
  {
    id: "5",
    name: "Start9",
    description: "Sovereign computing. Run your own personal server.",
    logo: "/assets/start9-logo.png",
    categories: ["💻 Electronics", "🌐 Hosting"],
    shippingCountries: ["🌍 Worldwide", "🇺🇸 USA"],
    website: "https://start9.com",
    lightningSupported: true,
    onchainSupported: true,
    featured: true,
    reviews: []
  },
  {
    id: "6",
    name: "Daylight Computer",
    description: "Building the first computer that feels like paper. The Daylight Tablet.",
    logo: "/assets/daylight-logo.png",
    categories: ["💻 Electronics"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://daylightcomputer.com",
    lightningSupported: false,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "7",
    name: "Tor Project",
    description: "Defending your rights to privacy and freedom online. Help us keep Tor strong.",
    logo: "/assets/tor-logo-new.png",
    categories: ["🛡️ VPN & Privacy", "❤️ Charity"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://torproject.org",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "8",
    name: "Namecheap",
    description: "Register domains and buy web hosting with Bitcoin. Privacy-focused domain registrar.",
    logo: "/assets/namecheap-logo.png",
    categories: ["🌐 Hosting"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://namecheap.com",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "9",
    name: "Human Rights Foundation",
    description: "Supporting civil society in closed societies and uniting people in the common cause of human rights.",
    logo: "/assets/hrf-logo.png",
    categories: ["❤️ Charity"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://hrf.org",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "10",
    name: "CheapAir",
    description: "Book flights and hotels with Bitcoin. One of the first travel sites to accept BTC.",
    logo: "/assets/cheapair-logo.png",
    categories: ["✈️ Travel"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://cheapair.com",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "11",
    name: "Travala",
    description: "Book 3,000,000+ travel products worldwide with Bitcoin and other cryptocurrencies.",
    logo: "/assets/travala-logo-new.png",
    categories: ["✈️ Travel"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://travala.com",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "12",
    name: "G2A",
    description: "The world's largest marketplace for digital entertainment. Buy games, gift cards, and software with Bitcoin.",
    logo: "/assets/g2a-logo-new.png",
    categories: ["🎁 Gift Cards"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://g2a.com",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "13",
    name: "Obscura",
    description: "High-performance VPN service built for the Bitcoin ecosystem. Privacy without compromise.",
    logo: "/assets/obscura-logo-new.png",
    categories: ["🛡️ VPN & Privacy"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://obscuravpn.com",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "14",
    name: "Silent.link",
    description: "Anonymously purchase eSIMs with Bitcoin. Privacy-first mobile data and SMS services.",
    logo: "/assets/silent-link-logo-new.png",
    categories: ["🛡️ VPN & Privacy"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://silent.link",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "15",
    name: "Great Ghee",
    description: "Handcrafted, small-batch ghee made from grass-fed butter. High-quality clarified butter for healthy cooking.",
    logo: "/assets/great-ghee-clean.png",
    categories: ["🍴 Food & Drink"],
    shippingCountries: ["🇺🇸 USA"],
    website: "https://greatghee.com",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "16",
    name: "Great North Air Ambulance",
    description: "Life-saving charity providing emergency medical care across the North of England. Supporting their operations via Bitcoin donations.",
    logo: "/assets/gnaas-logo-new.png",
    categories: ["❤️ Charity", "🏥 Health"],
    shippingCountries: ["🇬🇧 UK"],
    website: "https://www.greatnorthairambulance.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "17",
    name: "Castle Hill Gin",
    description: "Premium handcrafted gin distilled in the heart of Yorkshire. Traditional methods with modern botanical blends.",
    logo: "/assets/castle-hill-gin-new.png",
    categories: ["🍴 Food & Drink", "🍷 Alcohol"],
    shippingCountries: ["🇬🇧 UK"],
    website: "https://www.castlehillgin.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "18",
    name: "Bonjour Wines",
    description: "Specialist importer of fine French wines and artisanal spirits. Discover a curated selection of exceptional vineyards.",
    logo: "/assets/bonjour-wines-new.png",
    categories: ["🍴 Food & Drink", "🍷 Alcohol"],
    shippingCountries: ["🇬🇧 UK"],
    website: "https://www.bonjourwines.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "19",
    name: "Peony Lane Wine",
    description: "Artisan winery specializing in elegant, floral-noted wines. Experience the unique terroir of our boutique vineyards.",
    logo: "/assets/peony-lane-new.png",
    categories: ["🍴 Food & Drink", "🍷 Alcohol"],
    shippingCountries: ["🇺🇸 USA"],
    website: "https://www.peonylanewine.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "20",
    name: "Yum Yum Tree Fudge",
    description: "Premium handcrafted fudge made with natural ingredients. Discover a vast array of unique and traditional flavors from this artisan confectioner.",
    logo: "/assets/yum-yum-tree-fudge-new.png",
    categories: ["🍴 Food & Drink", "🍬 Sweets"],
    shippingCountries: ["🇬🇧 UK", "🌍 Worldwide"],
    website: "https://www.yumyumtreefudge.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "21",
    name: "Tea and Tonic",
    description: "British luxury skincare and wellness brand using high-performance adaptogens and sustainable ingredients to support body and mind.",
    logo: "/assets/tea-and-tonic-new.png",
    categories: ["💄 Health & Beauty", "🧘 Wellness"],
    shippingCountries: ["🇬🇧 UK", "🌍 Worldwide"],
    website: "https://www.teaandtonic.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "22",
    name: "AroTags",
    description: "Premium wood air fresheners for your car. Long-lasting, artisan-crafted scents using high-quality essential oils.",
    logo: "/assets/arotags-new.png",
    categories: ["🚗 Auto", "✨ Lifestyle"],
    shippingCountries: ["🇺🇸 USA", "🌍 Worldwide"],
    website: "https://www.arotags.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "23",
    name: "Spitting Feathers",
    description: "Award-winning independent brewery and pub. Crafting exceptional real ales and craft beers with a focus on quality and tradition.",
    logo: "/assets/spitting-feathers-fox.png",
    categories: ["🍴 Food & Drink", "🍷 Alcohol"],
    shippingCountries: ["🇬🇧 UK"],
    website: "https://spittingfeathers.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "24",
    name: "Mushmore Supplements",
    description: "Premium mushroom supplements crafted for optimal wellness. Harnessing the power of functional fungi for clarity, focus, and vitality.",
    logo: "/assets/mushmore-logo.png",
    categories: ["💄 Health & Beauty", "🧘 Wellness"],
    shippingCountries: ["🇺🇸 USA", "🌍 Worldwide"],
    website: "https://www.mushmoresupplements.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "25",
    name: "Hummingbird Amsterdam",
    description: "Specialty coffee bar and store in the heart of Amsterdam. Discover a curated selection of coffee beans and brewing equipment.",
    logo: "/assets/hummingbird-logo.png",
    categories: ["🍴 Food & Drink", "✨ Lifestyle"],
    shippingCountries: ["🇳🇱 Netherlands", "🇪🇺 Europe"],
    website: "https://www.hummingbird.amsterdam/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "26",
    name: "Planet Express",
    description: "Your premier package forwarding and shipping partner. Ship from the USA to anywhere in the world with ease and reliability.",
    logo: "/assets/planet-express-logo.png",
    categories: ["✨ Lifestyle"],
    shippingCountries: ["🇺🇸 USA", "🌍 Worldwide"],
    website: "https://planetexpress.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "27",
    name: "Farfetch",
    description: "The global destination for modern luxury. Shop the world's best designers and boutiques for clothing, shoes, and accessories.",
    logo: "/assets/farfetch-logo.png",
    categories: ["👗 Fashion", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.farfetch.com/",
    lightningSupported: false,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "28",
    name: "Bramleigh Farm",
    description: "Family-run regenerative farm in the KZN Midlands. Premium pasture-raised chicken, eggs, pork, and grass-fed beef delivered direct to your door.",
    logo: "/assets/bramleigh-logo.png",
    categories: ["🍴 Food & Drink", "🧘 Wellness"],
    shippingCountries: ["🇿🇦 South Africa"],
    website: "https://www.bramleigh.co.za/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "29",
    name: "Oshi Good",
    description: "Specialty coffee and cafe goods. Discover premium coffee beans and accessories for the perfect home brewing experience.",
    logo: "/assets/oshi-new.png",
    categories: ["🍴 Food & Drink", "✨ Lifestyle"],
    shippingCountries: ["🇺🇸 USA"],
    website: "https://www.oshigood.us/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "30",
    name: "Palingshop",
    description: "Traditional Dutch smoked eel and premium seafood delicacies delivered fresh from Volendam. Experience authentic Dutch flavors.",
    logo: "/assets/palingshop-logo.png",
    categories: ["🍴 Food & Drink"],
    shippingCountries: ["🇳🇱 Netherlands", "🇪🇺 Europe"],
    website: "https://www.palingshop.nl/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "31",
    name: "Ticketpro",
    description: "South Africa's leading ticketing provider for sports, concerts, and events. Book your next experience with Bitcoin.",
    logo: "/assets/ticketpro-logo.png",
    categories: ["🎬 Entertainment"],
    shippingCountries: ["🇿🇦 South Africa"],
    website: "https://www.ticketpro.co.za/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "32",
    name: "Dynadot",
    description: "Affordable domain registration and hosting services. Manage your digital identity with ease and security.",
    logo: "/assets/dynadot-logo.png",
    categories: ["⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.dynadot.com/",
    lightningSupported: false,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "33",
    name: "Soapminer",
    description: "Handcrafted natural soaps for Bitcoiners. High-quality ingredients and unique designs that celebrate the Bitcoin lifestyle.",
    logo: "/assets/soapminer-logo.png",
    categories: ["💄 Health & Beauty", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://soapminer.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "34",
    name: "MobiMatter",
    description: "The best eSIM marketplace for travelers. Get instant connectivity worldwide with affordable data plans.",
    logo: "/assets/mobimatter-logo.png",
    categories: ["✈️ Travel", "⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://mobimatter.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "35",
    name: "The Good Beans",
    description: "Ethically sourced, freshly roasted specialty coffee. Discover a wide variety of unique blends and single-origin beans.",
    logo: "/assets/thegoodbeans-logo.png",
    categories: ["🍴 Food & Drink", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://thegoodbeans.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "36",
    name: "Pumphreys Coffee",
    description: "Multi-award winning coffee roasters based in the North East of England since 1750. Specialists in finest quality coffee and tea.",
    logo: "/assets/pumphreys-logo.png",
    categories: ["🍴 Food & Drink", "✨ Lifestyle"],
    shippingCountries: ["🇬🇧 UK", "🌍 Worldwide"],
    website: "https://pumphreys-coffee.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "38",
    name: "Epic Deals",
    description: "South Africa's leading platform for pre-owned and new tech. Shop smartphones, tablets, and more with Bitcoin.",
    logo: "/assets/epicdeals-logo.png",
    categories: ["💻 Electronics", "⚙️ Tech"],
    shippingCountries: ["🇿🇦 South Africa"],
    website: "https://epicdeals.co.za/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "39",
    name: "Farmer Bill's Provisions",
    description: "Premium, craft beef jerky and meat snacks. Ethically sourced and packed with flavor, delivered to your door.",
    logo: "/assets/farmerbills-logo.png",
    categories: ["🍴 Food & Drink", "✨ Lifestyle"],
    shippingCountries: ["🇺🇸 USA"],
    website: "https://farmerbillsprovisions.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "40",
    name: "Acme Acres",
    description: "Pasture-raised heritage pork and poultry from a family-owned farm. Focused on ethical farming and sustainable practices.",
    logo: "/assets/acmeacres-logo.png",
    categories: ["🍴 Food & Drink", "✨ Lifestyle"],
    shippingCountries: ["🇺🇸 USA"],
    website: "https://acmeacres.us/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "41",
    name: "Chroma",
    description: "Chroma is dedicated to staying on the cutting edge of light therapy. Your support pushes forward devices designed by engineers who care deeply about health.",
    logo: "/assets/chroma-new.png",
    categories: ["⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://getchroma.co/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "42",
    name: "Kawa",
    description: "Specialty coffee roastery offering unique and flavorful beans. Experience the art of Japanese-inspired coffee roasting.",
    logo: "/assets/kawa-new.png",
    categories: ["🍴 Food & Drink", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.u2kawa.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "43",
    name: "Kijicha",
    description: "Authentic Japanese tea and premium matcha sourced directly from growers. Experience the tradition and serenity of high-quality tea.",
    logo: "/assets/kijicha-new.png",
    categories: ["🍴 Food & Drink", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://kijicha.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "44",
    name: "Leeds Gin",
    description: "Premium gin hand crafted in small batches in the heart of Yorkshire. Traditional botanicals steeped with juniper, coriander, ginger and orange.",
    logo: "https://www.leedsgin.com/wp-content/uploads/elementor/thumbs/cropped-Favicon-v2-01-plyh4y2k69gla83ozhwxsz3smo2eeooufuj8remsgw.png",
    categories: ["🍴 Food & Drink", "🍷 Alcohol"],
    shippingCountries: ["🇬🇧 UK"],
    website: "https://www.leedsgin.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "45",
    name: "ASF Tutoring",
    description: "Online Maths tutor specialising in 1-1 and small group tuition. Empowering young people to have confidence in their mathematical ability.",
    logo: "/assets/asf-tutoring-new.png",
    categories: ["⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.asftutoring.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "46",
    name: "The Suffolk Tutor",
    description: "Personalised primary school tutoring and specialist SEND support. Qualified teacher offering one-to-one and group sessions in Maths, English, and Science.",
    logo: "https://static.wixstatic.com/media/e7f737_461ad44966af488b8bdfee9c8146a001~mv2.png/v1/fill/w_385,h_465,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/%40thesuffolktutor.png",
    categories: ["⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide", "🇬🇧 UK"],
    website: "https://www.thesuffolktutor.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "47",
    name: "Jimble's Jumble",
    description: "Homemade preserves created in Northamptonshire from homegrown, wild foraged and food rescued ingredients. Small-batch jams, chutneys, and marmalades.",
    logo: "https://jimblesjumble.odoo.com/web/image/3369-f7e687f9/3-DSC_0022.webp",
    categories: ["🍴 Food & Drink", "✨ Lifestyle"],
    shippingCountries: ["🇬🇧 UK"],
    website: "https://jimblesjumble.odoo.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "48",
    name: "Hempful",
    description: "Premium European CBD and hemp products. High-potency, full-spectrum CBD oils, beverages, and skincare grown in the perfect climate for maximum potency.",
    logo: "/assets/hempful-new.png",
    categories: ["🍴 Food & Drink", "🧘 Wellness", "💄 Health & Beauty"],
    shippingCountries: ["🌍 Worldwide", "🇬🇧 UK", "🇪🇺 Europe"],
    website: "https://hempful.eu/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "49",
    name: "Highland Fayre",
    description: "Scotland's No. 1 specialist hamper company. Luxury food and wine hampers, gift baskets, and corporate gifts delivered throughout the UK.",
    logo: "/assets/highland-fayre-new.png",
    categories: ["🍴 Food & Drink", "🍷 Alcohol", "✨ Lifestyle"],
    shippingCountries: ["🇬🇧 UK"],
    website: "https://www.highlandfayre.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "50",
    name: "Golden Tallow",
    description: "Natural tallow skincare handcrafted from grass-fed beef suet. Traditional, nutrient-dense balms for healthy skin.",
    logo: "/assets/golden-tallow-new.png",
    categories: ["💄 Health & Beauty", "🧘 Wellness"],
    shippingCountries: ["🇺🇸 USA", "🌍 Worldwide"],
    website: "https://goldentallow.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "51",
    name: "Mister Padel",
    description: "Premium padel equipment and accessories. Discover high-performance rackets, bags, and apparel for padel enthusiasts.",
    logo: "/assets/mister-padel-new.png",
    categories: ["⚽ Sports", "✨ Lifestyle"],
    shippingCountries: ["🇪🇺 Europe", "🌍 Worldwide"],
    website: "https://misterpadel.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "52",
    name: "Lincoln Kiln Dried Logs",
    description: "Premium kiln dried firewood delivered across the UK. High-quality logs for wood burning stoves and open fires.",
    logo: "https://lincolnkilndriedlogs.co.uk/wp-content/uploads/2021/08/cropped-favicon-32x32.png",
    categories: ["✨ Lifestyle"],
    shippingCountries: ["🇬🇧 UK"],
    website: "https://lincolnkilndriedlogs.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "53",
    name: "Essatoshi",
    description: "Bitcoin-themed apparel and accessories. Minimalist designs that celebrate the Bitcoin culture and technology.",
    logo: "https://essatoshi.com/cdn/shop/files/essatoshi_logo_black_180x.png",
    categories: ["👕 Clothing", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://essatoshi.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "54",
    name: "Cheerings",
    description: "Custom engraved Bitcoin jewelry and unique keepsakes. Handcrafted pieces that tell your Bitcoin story.",
    logo: "/assets/cheerings-new.png",
    categories: ["🎨 Art", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://cheerings.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "55",
    name: "Jonathan Hill Luthier",
    description: "Bespoke handcrafted guitars and expert stringed instrument repair. Dedicated to the art of fine lutherie.",
    logo: "https://jonathanhillguitars.com/wp-content/uploads/2021/04/cropped-favicon-32x32.png",
    categories: ["🎨 Art", "🎵 Music"],
    shippingCountries: ["🇬🇧 UK", "🌍 Worldwide"],
    website: "https://jonathanhillguitars.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "56",
    name: "Select Automotive",
    description: "Independent luxury car specialist. Sourcing and providing premium pre-owned vehicles with a focus on quality and service.",
    logo: "https://www.selectautomotive.co.uk/wp-content/uploads/2021/05/cropped-favicon-32x32.png",
    categories: ["🚗 Auto", "✨ Lifestyle"],
    shippingCountries: ["🇬🇧 UK"],
    website: "https://www.selectautomotive.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "57",
    name: "CandyJets",
    description: "Experience the thrill of private aviation. Book private jet charters and luxury travel experiences with Bitcoin.",
    logo: "https://candyjets.com/wp-content/uploads/2021/05/cropped-favicon-32x32.png",
    categories: ["✈️ Travel", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://candyjets.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "58",
    name: "Maple AI",
    description: "Advanced AI solutions for business automation and data analysis. Leveraging cutting-edge technology to drive efficiency.",
    logo: "https://maple.ai/wp-content/uploads/2021/05/cropped-favicon-32x32.png",
    categories: ["⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://maple.ai/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "59",
    name: "PayperQ",
    description: "Innovative payment solutions for modern businesses. Streamlining transactions with a focus on security and speed.",
    logo: "https://payperq.com/wp-content/uploads/2021/05/cropped-favicon-32x32.png",
    categories: ["⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://payperq.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "60",
    name: "Crypto Tax Help",
    description: "Specialist cryptocurrency tax advice and accounting services. Navigating the complexities of crypto taxation for individuals and businesses.",
    logo: "https://cryptotaxhelp.co.uk/wp-content/uploads/2021/05/cropped-favicon-32x32.png",
    categories: ["⚙️ Tech"],
    shippingCountries: ["🇬🇧 UK", "🌍 Worldwide"],
    website: "https://cryptotaxhelp.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "61",
    name: "MtSocks",
    description: "Limited edition Bitcoin-themed socks that tell the story of Bitcoin's history. Collectible apparel for the discerning Bitcoiner.",
    logo: "https://www.mtsocks.com/static/images/favicon-32x32.png",
    categories: ["👕 Clothing", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.mtsocks.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "62",
    name: "TorGuard",
    description: "Anonymous VPN, proxy, and email services. Defend your online privacy with advanced encryption and security features.",
    logo: "https://torguard.net/images/favicon.png",
    categories: ["🛡️ VPN & Privacy"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://torguard.net/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "63",
    name: "Beef Initiative",
    description: "Connecting you directly to local ranchers for the highest quality pasture-raised beef. Focused on health, community, and decentralization.",
    logo: "https://beefinitiative.com/cdn/shop/files/BI_Logo_Black_180x.png",
    categories: ["🍴 Food & Drink", "🧘 Wellness"],
    shippingCountries: ["🇺🇸 USA"],
    website: "https://beefinitiative.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "64",
    name: "Spy Equipment UK",
    description: "Leading supplier of specialist spy equipment and surveillance solutions. Professional-grade tools for security and investigation.",
    logo: "https://www.spyequipmentuk.co.uk/skin/frontend/spyequipment/default/images/favicon.ico",
    categories: ["💻 Electronics", "⚙️ Tech"],
    shippingCountries: ["🇬🇧 UK", "🌍 Worldwide"],
    website: "https://www.spyequipmentuk.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "65",
    name: "Bees & Trees",
    description: "Premium New Zealand Manuka honey sourced directly from artisan beekeepers. High-activity honey with exceptional purity and flavor.",
    logo: "https://beesandtrees.com/cdn/shop/files/bees-and-trees-logo-black_180x.png",
    categories: ["🍴 Food & Drink", "🧘 Wellness"],
    shippingCountries: ["🇺🇸 USA", "🌍 Worldwide"],
    website: "https://beesandtrees.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "66",
    name: "Kaffebox",
    description: "Scandinavian specialty coffee subscription. Discover the best roasters from the Nordics delivered to your door every month.",
    logo: "https://www.kaffebox.no/wp-content/uploads/2016/06/kaffebox-logo-black-300x111.png",
    categories: ["🍴 Food & Drink", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.kaffebox.no/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "67",
    name: "Bloom Audio",
    description: "Specialist retailer of high-fidelity audio equipment. Discover premium headphones, DACs, and amplifiers for the ultimate listening experience.",
    logo: "https://bloomaudio.com/cdn/shop/files/bloom-audio-logo-black_180x.png",
    categories: ["💻 Electronics", "🎵 Music"],
    shippingCountries: ["🇺🇸 USA", "🌍 Worldwide"],
    website: "https://bloomaudio.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "68",
    name: "La Industria Handmade",
    description: "Handcrafted leather goods made with traditional techniques. High-quality wallets, bags, and accessories designed to last a lifetime.",
    logo: "/assets/la-industria-logo.png",
    categories: ["✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://laindustriahandmade.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "69",
    name: "Campo Apícola",
    description: "Organic honey and bee products from the heart of Spain. Supporting sustainable beekeeping and preserving traditional apiary methods.",
    logo: "/assets/campo-apicola-logo.png",
    categories: ["🍴 Food & Drink", "🧘 Wellness"],
    shippingCountries: ["🇪🇺 Europe", "🌍 Worldwide"],
    website: "https://campoapicola.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "70",
    name: "Elephant Chateau",
    description: "Premium Ceylon tea and exotic spices sourced directly from Sri Lanka. Experience the rich flavors and heritage of traditional agriculture.",
    logo: "/assets/elephant-chateau-logo.png",
    categories: ["🍴 Food & Drink", "✨ Lifestyle"],
    shippingCountries: ["🇺🇸 USA", "🌍 Worldwide"],
    website: "https://elephantchateau.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "71",
    name: "Árbol de Maple",
    description: "Premium Canadian maple syrup and gourmet maple products. Pure, artisan-crafted sweetness from the forests of Quebec.",
    logo: "/assets/arbol-de-maple-logo.png",
    categories: ["🍴 Food & Drink", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://arboldemaple.ca/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "72",
    name: "Consumer Choice Center",
    description: "Advocating for consumer choice and individual liberty worldwide. Supporting policies that empower consumers and foster innovation.",
    logo: "/assets/ccc-logo.png",
    categories: ["❤️ Charity"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://consumerchoicecenter.org/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "73",
    name: "Pikasim",
    description: "The ultimate destination for SIM cards and mobile data plans. Stay connected globally with affordable and reliable telecommunications.",
    logo: "/assets/pikasim-logo.png",
    categories: ["✈️ Travel", "⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://pikasim.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "74",
    name: "Mad Gringo Hot Sauce",
    description: "Artisan hot sauces handcrafted in small batches. Bold flavors and varying heat levels to elevate your culinary experience.",
    logo: "/assets/mad-gringo-logo.png",
    categories: ["🍴 Food & Drink", "✨ Lifestyle"],
    shippingCountries: ["🇺🇸 USA"],
    website: "https://madgringo.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "75",
    name: "PrivateRouter",
    description: "Pre-configured privacy routers for home and office. Secure your entire network with built-in VPN and encryption features.",
    logo: "/assets/privaterouter-logo.png",
    categories: ["💻 Electronics", "🛡️ VPN & Privacy"],
    shippingCountries: ["🇺🇸 USA", "🌍 Worldwide"],
    website: "https://privaterouter.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "76",
    name: "IVPN",
    description: "Privacy-focused VPN service with a strict no-logs policy. Defend your online freedom with advanced security tools and transparency.",
    logo: "/assets/ivpn-logo.png",
    categories: ["🛡️ VPN & Privacy"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.ivpn.net/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "77",
    name: "Hyke & Byke",
    description: "High-performance outdoor gear for backpacking and camping. Premium sleeping bags, tents, and apparel at an accessible price point.",
    logo: "/assets/hyke-byke-logo.png",
    categories: ["✨ Lifestyle"],
    shippingCountries: ["🇺🇸 USA", "🌍 Worldwide"],
    website: "https://www.hykeandbyke.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "78",
    name: "Kerwell",
    description: "Curated selection of premium CBD and wellness products. Discover high-quality tinctures, topicals, and edibles for optimal health.",
    logo: "/assets/kerwell-logo.png",
    categories: ["💄 Health & Beauty", "🧘 Wellness"],
    shippingCountries: ["🇺🇸 USA"],
    website: "https://kerwell.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "79",
    name: "Sticky",
    description: "Custom high-quality stickers and decals for personal and commercial use. Durable, vibrant designs to express your brand or personality.",
    logo: "/assets/sticky-logo.png",
    categories: ["🎨 Art", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://sticky.io/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "80",
    name: "Samen Maier",
    description: "Artisan seed company specializing in heirloom and organic varieties. Promoting biodiversity and sustainable gardening practices.",
    logo: "/assets/samen-maier-logo.png",
    categories: ["✨ Lifestyle"],
    shippingCountries: ["🇪🇺 Europe"],
    website: "https://www.samen-maier.at/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "81",
    name: "Smith Pastures",
    description: "Regenerative family farm providing grass-fed beef and pasture-raised poultry. Dedicated to soil health and animal welfare.",
    logo: "/assets/smith-pastures-logo.png",
    categories: ["🍴 Food & Drink", "🧘 Wellness"],
    shippingCountries: ["🇺🇸 USA"],
    website: "https://smithpastures.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "82",
    name: "SKOON.",
    description: "Eco-friendly, highly effective natural skincare. Harnessing the power of botanicals to deliver professional results for all skin types.",
    logo: "/assets/skoon-logo.png",
    categories: ["💄 Health & Beauty", "🧘 Wellness"],
    shippingCountries: ["🇿🇦 South Africa", "🌍 Worldwide"],
    website: "https://www.skoonskin.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "83",
    name: "Mei Leaf",
    description: "Discover the world's finest teas and authentic teaware. Direct sourcing and expert education from a leading tea house.",
    logo: "/assets/mei-leaf-logo.png",
    categories: ["🍴 Food & Drink", "✨ Lifestyle"],
    shippingCountries: ["🇬🇧 UK", "🌍 Worldwide"],
    website: "https://meileaf.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "84",
    name: "Missprint",
    description: "Award-winning British wallpaper and fabric design studio. Unique, hand-drawn patterns that bring character to any interior.",
    logo: "/assets/missprint-logo.png",
    categories: ["🎨 Art", "✨ Lifestyle"],
    shippingCountries: ["🇬🇧 UK", "🌍 Worldwide"],
    website: "https://www.missprint.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "85",
    name: "Izindlovu",
    description: "Conservation-focused jewelry and accessories. Supporting elephant protection and sustainable communities in Africa.",
    logo: "/assets/izindlovu-logo.png",
    categories: ["🎨 Art", "❤️ Charity"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://izindlovufund.be/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "86",
    name: "Sole",
    description: "Sustainable footwear and performance insoles. Designed for comfort and longevity using ethically sourced materials.",
    logo: "/assets/sole-logo.png",
    categories: ["👗 Fashion", "✨ Lifestyle"],
    shippingCountries: ["🇺🇸 USA", "🌍 Worldwide"],
    website: "https://yoursole.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "87",
    name: "FuelingYou",
    description: "Premium performance supplements and nutrition for athletes. Scientifically formulated to optimize training and recovery.",
    logo: "/assets/fuelingyou-logo.png",
    categories: ["🍴 Food & Drink", "🧘 Wellness"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://fuelingyou.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "88",
    name: "Root & Branch",
    description: "Artisan coffee roasters committed to ethical sourcing and exceptional flavor profiles. Experience the craft of specialty coffee.",
    logo: "/assets/root-and-branch-logo.png",
    categories: ["🍴 Food & Drink", "✨ Lifestyle"],
    shippingCountries: ["🇬🇧 UK", "🌍 Worldwide"],
    website: "https://rootandbranch.coffee/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "89",
    name: "Atoms",
    description: "The world's most comfortable everyday shoes. Precision-fit footwear designed for your daily journey.",
    logo: "/assets/atoms-logo.png",
    categories: ["👗 Fashion", "✨ Lifestyle"],
    shippingCountries: ["🇺🇸 USA", "🌍 Worldwide"],
    website: "https://atoms.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "90",
    name: "Heatbit",
    description: "The world's first heater that mines Bitcoin. Efficient, quiet heating for your home that earns you sats.",
    logo: "/assets/heatbit-logo.png",
    categories: ["💻 Electronics", "⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://heatbit.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "91",
    name: "NoGood Studio",
    description: "Full-service growth marketing agency helping businesses scale through data-driven strategies and creative execution.",
    logo: "/assets/nogood-logo.png",
    categories: ["⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://nogood.io/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "92",
    name: "DeGoogled",
    description: "Privacy-focused hardware and software solutions to reclaim your digital sovereignty. Say goodbye to Big Tech surveillance.",
    logo: "/assets/degoogled-logo.png",
    categories: ["💻 Electronics", "🛡️ VPN & Privacy"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://degoogled.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "93",
    name: "Crave",
    description: "Premium designer lifestyle and intimate wellness products. Award-winning designs focused on pleasure and sophisticated aesthetics.",
    logo: "/assets/crave-logo.png",
    categories: ["✨ Lifestyle", "🧘 Wellness"],
    shippingCountries: ["🇺🇸 USA", "🌍 Worldwide"],
    website: "https://lovecrave.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "94",
    name: "MMOGA",
    description: "Leading marketplace for digital keys, gamecards, and virtual currencies. Trusted provider for gaming enthusiasts since 2005.",
    logo: "/assets/mmoga-logo.png",
    categories: ["🎬 Entertainment", "🎁 Gift Cards"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.mmoga.com/",
    lightningSupported: false,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "95",
    name: "Human Trafficking Institute",
    description: "Decimating modern slavery by providing technical assistance and training to justice systems in trafficking hubs worldwide.",
    logo: "/assets/hti-logo.png",
    categories: ["❤️ Charity"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.traffickinginstitute.org/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "96",
    name: "Uzi Shop",
    description: "Curated streetwear and contemporary fashion from independent designers. Discover unique pieces for your urban lifestyle.",
    logo: "/assets/uzi-logo.png",
    categories: ["👕 Clothing", "👗 Fashion"],
    shippingCountries: ["🇺🇸 USA", "🌍 Worldwide"],
    website: "https://uzi-shop.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "97",
    name: "Le Cyclo Sportif",
    description: "Specialist cycling apparel and accessories for performance-driven riders. Precision-engineered gear for every climb and sprint.",
    logo: "/assets/le-cyclo-sportif-logo.png",
    categories: ["⚽ Sports", "✨ Lifestyle"],
    shippingCountries: ["🇦🇺 Australia", "🌍 Worldwide"],
    website: "https://lecyclosportif.com.au/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "98",
    name: "Hill Helicopters",
    description: "The world's first truly modern helicopter. Reimagining private aviation through advanced engineering and luxury design.",
    logo: "/assets/hill-helicopters-logo.png",
    categories: ["✈️ Travel", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.hillhelicopters.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "99",
    name: "Alternative Airlines",
    description: "Global flight search engine offering 600+ airlines. Book your next flight with Bitcoin and enjoy flexible payment options.",
    logo: "/assets/alternative-airlines-logo.png",
    categories: ["✈️ Travel"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.alternativeairlines.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "100",
    name: "Brazilian Botanicals",
    description: "Ethically sourced superfoods and medicinal herbs from the Amazon rainforest. Discover the power of traditional Brazilian wellness.",
    logo: "/assets/brazilian-botanicals-logo.png",
    categories: ["🍴 Food & Drink", "🧘 Wellness"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://brazilianbotanicals.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "101",
    name: "CyberPiggy",
    description: "Educational tools and hardware to help the next generation learn about Bitcoin and sound money in a fun, engaging way.",
    logo: "/assets/cyberpiggy-logo.png",
    categories: ["💻 Electronics", "⚙️ Tech"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://cyberpiggy.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "102",
    name: "NordVPN",
    description: "The world's leading VPN provider. Protect your digital life with advanced security features and a global server network.",
    logo: "/assets/nordvpn-logo.png",
    categories: ["🛡️ VPN & Privacy"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://nordvpn.com/",
    lightningSupported: false,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "103",
    name: "GameRoom",
    description: "Your ultimate destination for gaming hardware and peripherals. Build your dream setup with the best tech in the industry.",
    logo: "/assets/gameroom-logo.png",
    categories: ["💻 Electronics", "🎬 Entertainment"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://gameroom.tech/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "104",
    name: "Hotelgift",
    description: "The ultimate hotel gift card. Book stays at 750,000+ hotels worldwide with a single card, fully purchasable with Bitcoin.",
    logo: "/assets/hotelgift-logo.png",
    categories: ["✈️ Travel", "🎁 Gift Cards"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.hotelgift.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "105",
    name: "ReachTags",
    description: "NFC-powered digital business cards and networking solutions. Share your information instantly with a simple tap.",
    logo: "/assets/reachtags-logo.png",
    categories: ["⚙️ Tech", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://reachtags.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "106",
    name: "Surfshark",
    description: "Secure and affordable VPN service. Protect unlimited devices with advanced privacy tools and global server access.",
    logo: "/assets/surfshark-logo.png",
    categories: ["🛡️ VPN & Privacy"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://surfshark.com/",
    lightningSupported: false,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "107",
    name: "Vintage Guitar World",
    description: "Specialist dealer in rare and collectible vintage guitars. Discover iconic instruments from the golden era of guitar building.",
    logo: "/assets/vintage-guitar-world-logo.png",
    categories: ["🎨 Art", "🎵 Music"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.vintage-guitar-world.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "108",
    name: "Wayland Games",
    description: "Europe's largest independent tabletop hobby retailer. Shop wargames, board games, and miniatures with Bitcoin.",
    logo: "/assets/wayland-games-logo.png",
    categories: ["🎬 Entertainment", "✨ Lifestyle"],
    shippingCountries: ["🇪🇺 Europe", "🌍 Worldwide"],
    website: "https://www.waylandgames.co.uk/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "109",
    name: "ZenMarket",
    description: "Your gateway to shopping from Japan. Buy from Japanese online stores and auctions with ease and international shipping.",
    logo: "/assets/zenmarket-logo.png",
    categories: ["✈️ Travel", "✨ Lifestyle"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://zenmarket.jp/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "110",
    name: "Zumub",
    description: "Leading sports nutrition and wellness retailer. Shop supplements, vitamins, and healthy food for your active lifestyle.",
    logo: "/assets/zumub-logo.png",
    categories: ["🍴 Food & Drink", "🧘 Wellness"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.zumub.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "111",
    name: "Gift Off",
    description: "Purchase gift cards from hundreds of top brands with Bitcoin. The convenient way to shop everywhere with crypto.",
    logo: "/assets/gift-off-logo.png",
    categories: ["🎁 Gift Cards"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://giftoff.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "112",
    name: "Waking Herbs",
    description: "Curated selection of ethnobotanicals and traditional medicinal plants. Supporting biodiversity and ancestral wisdom.",
    logo: "/assets/waking-herbs-logo.png",
    categories: ["🍴 Food & Drink", "🧘 Wellness"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://www.wakingherbs.com/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "113",
    name: "Freedom of the Press Foundation",
    description: "Protecting, defending, and empowering public-interest journalism in the 21st century through technology and advocacy.",
    logo: "/assets/freedom-of-the-press-logo.png",
    categories: ["❤️ Charity"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://freedom.press/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  },
  {
    id: "114",
    name: "Internet Archive",
    description: "Building a digital library of Internet sites and other cultural artifacts in digital form. Support the history of the web.",
    logo: "/assets/internet-archive-logo.png",
    categories: ["❤️ Charity"],
    shippingCountries: ["🌍 Worldwide"],
    website: "https://archive.org/",
    lightningSupported: true,
    onchainSupported: true,
    reviews: []
  }
];
