import { db } from "./db";
import { merchants } from "@shared/schema";

export async function seed() {
  console.log("Seeding database...");

  const existing = await db.select().from(merchants);

  if (existing.length >= 56) {
    console.log(`Database already has ${existing.length} merchants. Skipping seed.`);
    return;
  }

  // Only seed if the table is completely empty (fresh deploy)
  if (existing.length > 0) {
    console.log(`Database has ${existing.length} merchants. Skipping seed to preserve data.`);
    return;
  }

  console.log("Empty database detected — inserting base merchants...");

  await db.insert(merchants).values([
    { name: "Proton", description: "Over 100 million people use Proton to stay private and secure online.", logo: "/assets/proton.png", categories: ["Email", "VPN", "Storage", "Documents", "Passwords", "Foundation"], shippingCountries: ["Worldwide"], website: "https://proton.me/", lightningSupported: false, onchainSupported: true, paymentProvider: "Self-hosted", countryMadeIn: "Switzerland", countryShippedFrom: "🇨🇭 Switzerland", lastSurveyed: "2026-02-18" },
    { name: "FARFETCH", description: "The global destination for modern luxury.", logo: "/assets/farftech.png", categories: ["Fashion", "Lifestyle"], shippingCountries: ["Worldwide"], website: "https://www.farfetch.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Triple A", countryMadeIn: "United Kingdom", countryShippedFrom: "🇬🇧 UK", lastSurveyed: "2026-02-15" },
    { name: "Name Cheap", description: "Register domains and buy web hosting with Bitcoin. Privacy-focused domain registrar.", logo: "/assets/namecheap.png", categories: ["Hosting"], shippingCountries: ["Worldwide"], website: "https://www.namecheap.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "BTCPay Server", countryMadeIn: "United States", lastSurveyed: "2026-02-15" },
    { name: "The Human Rights Foundation", description: "Uniting people under the common cause of defending human rights and promoting liberal democracy.", logo: "/assets/humanrightsfoundation.png", categories: ["Charity"], shippingCountries: ["Worldwide"], website: "https://hrf.org/", lightningSupported: true, onchainSupported: true, paymentProvider: "BTCPay Server", countryMadeIn: "United States", lastSurveyed: "2026-02-15" },
    { name: "SLNT", description: "Privacy-first Faraday bags and signal blocking accessories.", logo: "/assets/slnt.png", categories: ["Privacy", "Fashion", "Health"], shippingCountries: ["Worldwide"], website: "https://slnt.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Strike", countryMadeIn: "United States", lastSurveyed: "2026-02-15", bitcoinDiscount: "NEW" },
    { name: "Travala", description: "Book hotels, flights, tours and activities.", logo: "/assets/travala.png", categories: ["Travel"], shippingCountries: ["Worldwide"], website: "https://www.travala.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Open Node", countryMadeIn: "Singapore", lastSurveyed: "2026-02-15" },
    { name: "Bees and Trees", description: "Unlock nature's goodness with high-quality organic Manuka Honey", logo: "/assets/beesandtrees.png", categories: ["Food & Drink"], shippingCountries: ["Worldwide"], website: "https://www.beesandtrees.com/", lightningSupported: true, onchainSupported: false, paymentProvider: "Strike", countryMadeIn: "New Zealand", lastSurveyed: "2026-02-15" },
    { name: "Polymarket", description: "The world's largest prediction market.", logo: "/assets/polymarket.png", categories: ["Gambling"], shippingCountries: ["Worldwide"], website: "https://polymarket.com/", lightningSupported: false, onchainSupported: true, paymentProvider: "Self-hosted", countryMadeIn: "United States", lastSurveyed: "2026-02-15" },
    { name: "Maple AI", description: "Private AI chat with end-to-end encryption.", logo: "/assets/mapleai.png", categories: ["AI", "Privacy", "Open-source"], shippingCountries: ["Worldwide"], website: "https://trymaple.ai/", lightningSupported: true, onchainSupported: true, paymentProvider: "Zaprite", countryMadeIn: "United States", lastSurveyed: "2026-02-15", bitcoinDiscount: "10% off with BTC" },
    { name: "Hill Helicopters", description: "Experience the future of private helicopter aviation.", logo: "/assets/hillhelicopters.png", categories: ["Vehicle"], shippingCountries: ["Worldwide"], website: "https://www.hillhelicopters.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "CoinCorner", countryMadeIn: "United Kingdom", lastSurveyed: "2026-02-15" },
    { name: "Atoms", description: "The most comfortable shoes for everyday wear.", logo: "/assets/atoms.png", categories: ["Fashion"], shippingCountries: ["Worldwide"], website: "https://atoms.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Open Node", countryMadeIn: "United States", lastSurveyed: "2026-02-15" },
    { name: "Mullvad VPN", description: "VPN service that helps keep your online activity, identity, and location private.", logo: "/assets/mullvad.png", categories: ["VPN", "Privacy", "Browser"], shippingCountries: ["Worldwide"], website: "https://mullvad.net/en", lightningSupported: true, onchainSupported: true, paymentProvider: "Self-hosted", countryMadeIn: "Sweden", lastSurveyed: "2026-02-15" },
    { name: "Overstock", description: "Find the best online deals on everything for your home and more.", logo: "/assets/overstock.png", categories: ["Home Goods", "Jewellery"], shippingCountries: ["United States"], website: "https://www.overstock.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "COINPAYMENTS", countryMadeIn: "United States", lastSurveyed: "2026-02-15" },
    { name: "Signal", description: "Share text, voice messages, photos, videos, GIFs and files for free securely.", logo: "/assets/signal.png", categories: ["Social Media", "Privacy", "Foundation", "Open-source"], shippingCountries: ["Worldwide"], website: "https://signal.org/", lightningSupported: false, onchainSupported: true, paymentProvider: "The Giving Block", countryMadeIn: "United States", lastSurveyed: "2026-02-15" },
    { name: "Cheap Air", description: "Experience cheap, fast and secure flight bookings.", logo: "/assets/cheapair.png", categories: ["Travel"], shippingCountries: ["Worldwide"], website: "https://www.cheapair.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "BTCPay Server", countryMadeIn: "United States", lastSurveyed: "2026-02-15" },
    { name: "PayPerQ", description: "Pay per prompt and get instant access to hundreds of powerful AI models. No subscriptions. No registration required.", logo: "/assets/payperq.png", categories: ["AI", "Digital Privacy"], shippingCountries: ["Worldwide"], website: "https://ppq.ai/", lightningSupported: true, onchainSupported: true, paymentProvider: "BTCPay Server", countryMadeIn: null, lastSurveyed: "2026-02-15", bitcoinDiscount: "5% off with BTC" },
    { name: "Nord VPN", description: "Fast, secure, and risk-free VPN for online privacy.", logo: "/assets/nordvpn.png", categories: ["VPN", "Privacy", "Cellular", "Password Manager", "Storage", "Insurance"], shippingCountries: ["Worldwide"], website: "https://nordvpn.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Coingate", countryMadeIn: null, lastSurveyed: "2026-02-15" },
    { name: "Beef initiative", description: "Order beef that is more localized, redundant, and secure.", logo: "/assets/beefinitiative.png", categories: ["Food & Drink"], shippingCountries: ["United States"], website: "https://beefinitiative.com/", lightningSupported: true, onchainSupported: false, paymentProvider: "Strike", countryMadeIn: "United States", lastSurveyed: "2026-02-15" },
    { name: "Daylight Computer", description: "Healthy and humane computers that respect our health, attention and freedom.", logo: "/assets/daylight.png", categories: ["Electronics", "Health"], shippingCountries: ["Worldwide"], website: "https://daylightcomputer.com/", lightningSupported: true, onchainSupported: false, paymentProvider: "Strike", countryMadeIn: "United States", lastSurveyed: "2026-02-15" },
    { name: "Wayland Games", description: "Europe's largest independent retailer for tabletop games and miniatures.", logo: "/assets/waylandgames.png", categories: ["Toys & Boardgames"], shippingCountries: ["Europe"], website: "https://www.waylandgames.co.uk/", lightningSupported: true, onchainSupported: true, paymentProvider: "Coingate", countryMadeIn: "United Kingdom", lastSurveyed: "2026-02-15" },
    { name: "Sole", description: "Footbeds that deliver unrivaled comfort and support.", logo: "/assets/sole.png", categories: ["Fashion", "Health"], shippingCountries: ["Worldwide"], website: "https://yoursole.com/", lightningSupported: true, onchainSupported: false, paymentProvider: "Unknown", countryMadeIn: "Canada", lastSurveyed: "2026-02-15" },
    { name: "Chroma", description: "High performance light therapy solutions", logo: "/assets/chroma.png", categories: ["Electronics", "Health"], shippingCountries: ["Worldwide"], website: "https://getchroma.co/", lightningSupported: false, onchainSupported: true, paymentProvider: "BTCPay Server", countryMadeIn: "United States", lastSurveyed: "2026-02-15" },
    { name: "Tor", description: "We advance human rights and defend your privacy online through free software and open networks.", logo: "/assets/tor.png", categories: ["VPN", "Privacy", "Charity", "Open-source"], shippingCountries: ["Worldwide"], website: "https://www.torproject.org/", lightningSupported: true, onchainSupported: true, paymentProvider: "BTCPay Server", countryMadeIn: null, lastSurveyed: "2026-02-15" },
    { name: "Hostinger", description: "Build, host, and grow online projects with domains.", logo: "/assets/hostinger.png", categories: ["Hosting"], shippingCountries: ["Worldwide"], website: "https://www.hostinger.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Coingate", countryMadeIn: "Lithuania", lastSurveyed: "2026-02-15" },
    { name: "Hotel Gift", description: "The #1 best-selling hotel gift card redeemable on 750000+ hotels and 1200+ hotel chains in more than 170 countries worldwide.", logo: "/assets/hotelgift.png", categories: ["Giftcard", "Travel"], shippingCountries: ["Worldwide"], website: "https://www.hotelgift.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Coingate", countryMadeIn: "Netherlands", lastSurveyed: "2026-02-15" },
    { name: "Crave Picks", description: "Toothpicks designed for adults who want a cleaner, more discreet way to enjoy nicotine", logo: "/assets/cravepicks.png", categories: ["Niccotine", "Adult"], shippingCountries: ["Worldwide"], website: "https://cravepicks.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "BTCPay Server", countryMadeIn: "United States", lastSurveyed: "2026-02-15" },
    { name: "Jetcraft", description: "The global leader in business aircraft sales, acquisitions and trades.", logo: "/assets/jetcraft.png", categories: ["Travel"], shippingCountries: ["Worldwide"], website: "https://www.jetcraft.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "COINPAYMENTS", countryMadeIn: "United States", lastSurveyed: "2026-02-15" },
    { name: "Amnesty International", description: "Support Human Rights and Freedoms.", logo: "/assets/amnestyinternational.png", categories: ["Charity"], shippingCountries: ["Worldwide"], website: "https://www.amnesty.org/en/", lightningSupported: false, onchainSupported: true, paymentProvider: "The Giving Block", countryMadeIn: "United States", lastSurveyed: "2026-02-15" },
    { name: "Bloom Audio", description: "The most friendly and customer service obsessed store for the world's best audiophile brands", logo: "/assets/bloomaudio.png", categories: ["Electronics"], shippingCountries: ["Worldwide"], website: "https://bloomaudio.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Open Node", countryMadeIn: "United States", lastSurveyed: "2026-02-15" },
    { name: "Bitrefill", description: "Shop for Gift Cards, eSIMs, and Mobile Recharges with BTC", logo: "/assets/bitrefill.png", categories: ["Giftcards", "Cellular"], shippingCountries: ["Worldwide"], website: "https://www.bitrefill.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Self-hosted", countryMadeIn: "Sweden", lastSurveyed: "2026-02-15" },
    { name: "Obscura VPN", description: "\"No-log\" VPNs can track you but we are designed to be provably private, as it is technically impossible for us to see your traffic or logs.", logo: "/assets/obscura.png", categories: ["VPN", "Privacy", "Open-source"], shippingCountries: ["Worldwide"], website: "https://obscura.net/", lightningSupported: true, onchainSupported: false, paymentProvider: "Self-hosted", countryMadeIn: "United States", lastSurveyed: "2026-02-15" },
    { name: "Maxim", description: "Catering to the modern man with content that promises to seduce, entertain and continuously surprise readers.", logo: "/assets/maxim.png", categories: ["Publication", "Lifestyle"], shippingCountries: ["Worldwide"], website: "https://www.maxim.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Speed", countryMadeIn: null, lastSurveyed: "2026-02-15" },
    { name: "Alternative Airlines", description: "Book flights to anywhere in the world on 600+ airlines with 40+ payment methods.", logo: "/assets/alternativeairlines.png", categories: ["Travel"], shippingCountries: ["Worldwide"], website: "https://www.alternativeairlines.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Coingate", countryMadeIn: null, lastSurveyed: "2026-02-15" },
    { name: "Grab", description: "The all-in-one platform for rides, delivery, payments and insurance.", logo: "/assets/grab.png", categories: ["Food & Drink", "Delivery", "Travel", "Insurance", "Payments"], shippingCountries: ["Singapore"], website: "https://www.grab.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Triple A", countryMadeIn: "Singapore", lastSurveyed: "2026-02-15" },
    { name: "LaHaus", description: "Digital real estate marketplace that specializes in the sale of new residential properties in Mexico and Columbia.", logo: "/assets/lahaus.png", categories: ["Real Estate"], shippingCountries: ["Mexico", "Columbia"], website: "https://www.lahaus.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Coingate", countryMadeIn: "Columbia", lastSurveyed: "2026-02-15" },
    { name: "Super Yachts Monaco", description: "Boutique brokerage headquartered in Monaco and operating globally.", logo: "/assets/superyachtsmonaco.png", categories: ["Vehicles"], shippingCountries: [], website: "https://www.superyachtsmonaco.com/", lightningSupported: true, onchainSupported: false, paymentProvider: "Bitcashier", countryMadeIn: "Monaco", lastSurveyed: "2026-02-15" },
    { name: "Trade It", description: "Instantly Trade, Buy or Sell CS2, RUST, and TF2 skins for the lowest fees!", logo: "/assets/tradeit.png", categories: ["Gaming"], shippingCountries: ["Worldwide"], website: "https://tradeit.gg/", lightningSupported: true, onchainSupported: true, paymentProvider: "NOWPayments", countryMadeIn: "United States", lastSurveyed: "2026-02-15" },
    { name: "OpenSats", description: "Funding free and open-source software and projects, particularly those related to Bitcoin, Nostr, and \"freedom tech,\" including protocol development and privacy tools.", logo: "/assets/opensats.png", categories: ["Charity", "Open-source"], shippingCountries: ["Worldwide"], website: "https://opensats.org/", lightningSupported: true, onchainSupported: true, paymentProvider: "BTCPay Server", countryMadeIn: "United States", lastSurveyed: "2026-02-15" },
    { name: "Stake", description: "Play the best online casino games, slots & live casino games, or bet on sports", logo: "/assets/stake.png", categories: ["Gambling"], shippingCountries: ["Worldwide"], website: "https://stake.com/", lightningSupported: false, onchainSupported: true, paymentProvider: "Self-hosted", countryMadeIn: "Curacoa", lastSurveyed: "2026-02-15" },
    { name: "Aqua Living", description: "Discover premium hot tubs, swim spas, and cold tubs.", logo: "/assets/aqualiving.png", categories: ["Lifestyle"], shippingCountries: ["United States"], website: "https://hottub.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Speed", countryMadeIn: "United States", lastSurveyed: "2026-02-15" },
    { name: "Mirai Flights", description: "Instantly book private jets and empty legs worldwide with real-time fixed pricing.", logo: "/assets/miraiflights.png", categories: ["Travel"], shippingCountries: ["Worldwide"], website: "https://mirai.flights/", lightningSupported: false, onchainSupported: true, paymentProvider: "CoinsPaid", countryMadeIn: "United Kingdom", lastSurveyed: "2026-02-15" },
    { name: "Rumble", description: "Your rights management video platform. Host, distribute and monetize all your professional, social and viral video.", logo: "/assets/rumble.png", categories: ["Social Media"], shippingCountries: ["Worldwide"], website: "https://rumble.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Self-hosted", countryMadeIn: "United States", lastSurveyed: "2026-02-15" },
    { name: "Dope Gallery", description: "A wide selection of prints, sculptures, art toys, photography and original paintings by names such as Takashi Murakami, Banksy, Kaws, Bearbrick, Edgar Plans", logo: "/assets/dopegallary.png", categories: ["Art"], shippingCountries: ["Worldwide"], website: "https://dope.gallery/", lightningSupported: true, onchainSupported: true, paymentProvider: "NOWPayments", countryMadeIn: null, lastSurveyed: "2026-02-15" },
    { name: "St Judes Children's Research Hospital", description: "A leading children's hospital, St. Jude treats the toughest childhood cancers and pediatric diseases.", logo: "/assets/stjudes.png", categories: ["Charity"], shippingCountries: ["Worldwide"], website: "https://www.stjude.org/", lightningSupported: false, onchainSupported: true, paymentProvider: "The Giving Block", countryMadeIn: "United States", lastSurveyed: "2026-02-15" },
    { name: "RPG Stash", description: "Buy Game Items and Services since its launch in 2004.", logo: "/assets/rpgstash-mloe9vti.png", categories: ["Gaming"], shippingCountries: ["Worldwide"], website: "https://www.rpgstash.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Open Node", countryMadeIn: "United Arab Emirates", lastSurveyed: "2026-02-15" },
    { name: "Primal", description: "Social media app where you control your identity, content and algorithm with the right to exit.", logo: "/assets/primal.png", categories: ["Social Media"], shippingCountries: ["Worldwide"], website: "https://primal.net/", lightningSupported: true, onchainSupported: false, paymentProvider: "Strike", countryMadeIn: null, lastSurveyed: "2026-02-15" },
    { name: "Cloaked Wireless", description: "Privacy & security-focused wireless provider; the best protection from SIM swap attacks.", logo: "/assets/cloakedwireless.png", categories: ["Cellular", "Privacy"], shippingCountries: ["United States"], website: "https://cloakedwireless.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Self-hosted", countryMadeIn: "United States", lastSurveyed: "2026-02-18" },
    { name: "SALT OF THE EARTH", description: "Premium, zero-sugar electrolyte drink mix designed to combat fatigue and improve hydration using Pink Himalayan Salt and essential minerals.", logo: "/assets/saltoftheearth.png", categories: ["Food & Drink", "Supplement"], shippingCountries: ["Worldwide"], website: "https://drinksote.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Strike", countryMadeIn: "United States", lastSurveyed: "2026-02-18" },
    { name: "NICNAC", description: "Niccotine bricks with no hidden ingredients.", logo: "/api/logos/nicnac-movp7cxn.png", categories: ["Niccotine"], shippingCountries: ["🇪🇺 Europe", "🇬🇧 UK", "🇺🇸 USA"], website: "www.nicnac.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Strike", countryMadeIn: "🇺🇸 USA", countryShippedFrom: "🇺🇸 USA", lastSurveyed: "2026-05-07", bitcoinDiscount: "NEW" },
    { name: "MOD BIKES", description: "Customizable e-bikes.", logo: "/api/logos/mod-bikes-movps511.png", categories: ["Vehicle", "Toys & Boardgames"], shippingCountries: ["🇺🇸 USA", "🇨🇦 Canada"], website: "https://www.mod-bikes.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Strike", countryMadeIn: "🇺🇸 USA", countryShippedFrom: "🇺🇸 USA", lastSurveyed: "2026-05-07", bitcoinDiscount: "2% OFF WITH BTC" },
    { name: "Autonomous", description: "Office desk, chairs and buildings.", logo: "/api/logos/autonomous-movrnw96.png", categories: ["Home Goods"], shippingCountries: ["🌍 Worldwide"], website: "www.autonomous.ai/", lightningSupported: true, onchainSupported: true, paymentProvider: "Self-hosted", countryMadeIn: "🇺🇸 USA", countryShippedFrom: "🇺🇸 USA", lastSurveyed: "2026-05-07", bitcoinDiscount: "3% OFF WITH BTC" },
    { name: "Nada Nada", description: "Anonymous VPNs, SMS and e-SIMs.", logo: "/api/logos/nada-nada-movt0w4i.png", categories: ["Cellular", "Digital Privacy"], shippingCountries: ["🌍 Worldwide"], website: "nadanada.me/", lightningSupported: true, onchainSupported: true, paymentProvider: "Self-hosted", countryMadeIn: null, lastSurveyed: "2026-05-07", bitcoinDiscount: "5% OFF WITH BTC" },
    { name: "G2G", description: "Videogame marketplace.", logo: "/api/logos/g2g-movuhx5u.png", categories: ["Gaming"], shippingCountries: ["🌍 Worldwide"], website: "www.g2g.com", lightningSupported: true, onchainSupported: true, paymentProvider: "Triple A", countryMadeIn: "🇲🇾 Malaysia", lastSurveyed: "2026-05-07" },
    { name: "Suisse Gold", description: "Precious metals dealer.", logo: "/api/logos/suisse-gold-1--movzow5s.png", categories: ["🪙 Precious metals"], shippingCountries: ["🌍 Worldwide"], website: "https://suissegold.com/", lightningSupported: false, onchainSupported: true, paymentProvider: "Self-hosted", countryMadeIn: "🇨🇭 Switzerland", countryShippedFrom: "🇨🇭 Switzerland", lastSurveyed: "2026-05-07" },
    { name: "Save the Children", description: "A leading humanitarian organization for children that has changed the lives of over 1 billion children around the world.", logo: "/assets/savethechildren.png", categories: ["Charity"], shippingCountries: ["Worldwide"], website: "https://www.savethechildren.org/", lightningSupported: false, onchainSupported: true, paymentProvider: "The Giving Block", countryMadeIn: null, lastSurveyed: "2026-02-15" },
    { name: "AROTAGS", description: "Premium wood air fresheners for your car. Long-lasting, artisan-crafted scents.", logo: "/assets/arotags.png", categories: ["Lifestyle", "Vehicle"], shippingCountries: ["Worldwide"], website: "https://www.arotags.com/", lightningSupported: true, onchainSupported: false, paymentProvider: "Strike", countryMadeIn: "United States", lastSurveyed: "2026-02-15" },
  ]);

  console.log("Seed complete: inserted 56 merchants.");
}

const isDirectRun = process.argv[1]?.includes('seed');
if (isDirectRun) {
  seed()
    .then(() => {
      console.log("Seed complete.");
      process.exit(0);
    })
    .catch((err) => {
      console.error("Seed failed:", err);
      process.exit(1);
    });
}
