import { db } from "./db";
import { merchants } from "@shared/schema";

const SEED_MERCHANTS = [
  { name: "Farfetch", description: "The global destination for modern luxury.", logo: "", categories: ["Fashion", "Lifestyle"], shippingCountries: ["🌍 Worldwide"], website: "https://www.farfetch.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Triple A", countryMadeIn: "United Kingdom" },
  { name: "Namecheap", description: "Register domains and buy web hosting with Bitcoin. Privacy-focused domain registrar.", logo: "", categories: ["🌐 Hosting"], shippingCountries: ["🌍 Worldwide"], website: "https://www.namecheap.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "BTCPay Server", countryMadeIn: "United States" },
  { name: "The Human Rights Foundation", description: "Uniting people under the common cause of defending human rights and promoting liberal democracy.", logo: "", categories: ["❤️ Charity"], shippingCountries: ["🌍 Worldwide"], website: "https://hrf.org/", lightningSupported: true, onchainSupported: true, paymentProvider: "BTCPay Server", countryMadeIn: "United States" },
  { name: "SLNT", description: "Privacy-first Faraday bags and signal blocking accessories.", logo: "", categories: ["Fashion", "🛡️ VPN & Privacy", "Health"], shippingCountries: ["🌍 Worldwide"], website: "https://slnt.com/", lightningSupported: true, onchainSupported: false, paymentProvider: "Strike", countryMadeIn: "United States" },
  { name: "Travala", description: "Book hotels, flights, tours and activities.", logo: "", categories: ["✈️ Travel"], shippingCountries: ["🌍 Worldwide"], website: "https://www.travala.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Open Node", countryMadeIn: "Singapore" },
  { name: "Mullvad VPN", description: "VPN service that helps keep your online activity, identity, and location private.", logo: "", categories: ["🛡️ VPN & Privacy", "VPN"], shippingCountries: ["🌍 Worldwide"], website: "https://mullvad.net/en", lightningSupported: true, onchainSupported: true, paymentProvider: "Self-hosted", countryMadeIn: "Sweden" },
  { name: "Maple AI", description: "Private AI chat with end-to-end encryption.", logo: "", categories: ["AI", "🛡️ VPN & Privacy"], shippingCountries: ["🌍 Worldwide"], website: "https://trymaple.ai/", lightningSupported: true, onchainSupported: true, paymentProvider: "Zaprite", countryMadeIn: "United States" },
  { name: "Polymarket", description: "The world's largest prediction market.", logo: "", categories: ["Gambling"], shippingCountries: ["🌍 Worldwide"], website: "https://polymarket.com/", lightningSupported: false, onchainSupported: true, paymentProvider: "Self-hosted", countryMadeIn: "United States" },
  { name: "Overstock", description: "Find the best online deals on everything for your home and more.", logo: "", categories: ["Home Goods", "Furniture", "Jewellery"], shippingCountries: ["United States"], website: "https://www.overstock.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "COINPAYMENTS", countryMadeIn: "United States" },
  { name: "AROTAGS", description: "Premium wood air fresheners for your car. Long-lasting, artisan-crafted scents.", logo: "", categories: ["Vehicle", "Lifestyle"], shippingCountries: ["🌍 Worldwide"], website: "https://www.arotags.com/", lightningSupported: true, onchainSupported: false, paymentProvider: "Strike", countryMadeIn: "United States" },
  { name: "Atoms", description: "The most comfortable shoes for everyday wear.", logo: "", categories: ["Footwear"], shippingCountries: ["🌍 Worldwide"], website: "https://atoms.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Open Node", countryMadeIn: "United States" },
  { name: "Hill Helicopters", description: "Experience the future of private helicopter aviation.", logo: "", categories: ["Vehicle"], shippingCountries: ["🌍 Worldwide"], website: "https://www.hillhelicopters.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "CoinCorner", countryMadeIn: "United Kingdom" },
  { name: "Signal", description: "Share text, voice messages, photos, videos, GIFs and files for free securely.", logo: "", categories: ["❤️ Charity", "🛡️ VPN & Privacy", "Social Media"], shippingCountries: ["🌍 Worldwide"], website: "https://signal.org/", lightningSupported: false, onchainSupported: true, paymentProvider: "The Giving Block", countryMadeIn: "United States" },
  { name: "Cheap Air", description: "Experience cheap, fast and secure flight bookings.", logo: "", categories: ["✈️ Travel"], shippingCountries: ["🌍 Worldwide"], website: "https://www.cheapair.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "BTCPay Server", countryMadeIn: "United States" },
  { name: "Save the Children", description: "A leading humanitarian organization for children that has changed the lives of over 1 billion children around the world.", logo: "", categories: ["❤️ Charity"], shippingCountries: ["🌍 Worldwide"], website: "https://www.savethechildren.org/", lightningSupported: false, onchainSupported: true, paymentProvider: "The Giving Block" },
  { name: "Bees and Trees", description: "Unlock nature's goodness with high-quality organic Manuka Honey", logo: "", categories: ["🍴 Food & Drink"], shippingCountries: ["🌍 Worldwide"], website: "https://www.beesandtrees.com/", lightningSupported: true, onchainSupported: false, paymentProvider: "Strike", countryMadeIn: "New Zealand" },
  { name: "Nord VPN", description: "Fast, secure, and risk-free VPN for online privacy.", logo: "", categories: ["🛡️ VPN & Privacy", "VPN"], shippingCountries: ["🌍 Worldwide"], website: "https://nordvpn.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Coingate" },
  { name: "PayPerQ", description: "Pay per prompt and get instant access to hundreds of powerful AI models. No subscriptions. No registration required.", logo: "", categories: ["AI"], shippingCountries: ["🌍 Worldwide"], website: "https://ppq.ai/", lightningSupported: true, onchainSupported: true, paymentProvider: "BTCPay Server" },
  { name: "Daylight Computer", description: "Healthy and humane computers that respect our health, attention and freedom.", logo: "", categories: ["💻 Electronics"], shippingCountries: ["🌍 Worldwide"], website: "https://daylightcomputer.com/", lightningSupported: true, onchainSupported: false, paymentProvider: "Strike", countryMadeIn: "United States" },
  { name: "Beef Initiative", description: "Order beef that is more localized, redundant, and secure.", logo: "", categories: ["🍴 Food & Drink"], shippingCountries: ["United States"], website: "https://beefinitiative.com/", lightningSupported: true, onchainSupported: false, paymentProvider: "Strike", countryMadeIn: "United States" },
  { name: "Chroma", description: "High performance light therapy solutions", logo: "", categories: ["Lifestyle"], shippingCountries: ["🌍 Worldwide"], website: "https://getchroma.co/", lightningSupported: false, onchainSupported: true, paymentProvider: "BTCPay Server", countryMadeIn: "United States" },
  { name: "Sole", description: "Footbeds that deliver unrivaled comfort and support.", logo: "", categories: ["Fashion"], shippingCountries: ["🌍 Worldwide"], website: "https://yoursole.com/", lightningSupported: true, onchainSupported: false, paymentProvider: "Unknown", countryMadeIn: "Canada" },
  { name: "Wayland Games", description: "Europe's largest independent retailer for tabletop games and miniatures.", logo: "", categories: ["Games"], shippingCountries: ["EEA"], website: "https://www.waylandgames.co.uk/", lightningSupported: true, onchainSupported: true, paymentProvider: "Coingate", countryMadeIn: "United Kingdom" },
  { name: "Tor", description: "We advance human rights and defend your privacy online through free software and open networks.", logo: "", categories: ["🛡️ VPN & Privacy", "❤️ Charity"], shippingCountries: ["🌍 Worldwide"], website: "https://www.torproject.org/", lightningSupported: true, onchainSupported: true, paymentProvider: "BTCPay Server" },
  { name: "Hostinger", description: "Build, host, and grow online projects with domains.", logo: "", categories: ["🌐 Hosting"], shippingCountries: ["🌍 Worldwide"], website: "https://www.hostinger.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Coingate", countryMadeIn: "Lithuania" },
  { name: "Hotel Gift", description: "The #1 best-selling hotel gift card redeemable on 750000+ hotels and 1200+ hotel chains in more than 170 countries worldwide.", logo: "", categories: ["🎁 Gift Cards", "✈️ Travel"], shippingCountries: ["🌍 Worldwide"], website: "https://www.hotelgift.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Coingate", countryMadeIn: "Netherlands" },
  { name: "Jetcraft", description: "The global leader in business aircraft sales, acquisitions and trades.", logo: "", categories: ["Airplanes"], shippingCountries: ["🌍 Worldwide"], website: "https://www.jetcraft.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "COINPAYMENTS", countryMadeIn: "United States" },
  { name: "Crave Picks", description: "Toothpicks designed for adults who want a cleaner, more discreet way to enjoy nicotine", logo: "", categories: ["Nicotine"], shippingCountries: ["🌍 Worldwide"], website: "https://cravepicks.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "BTCPay Server", countryMadeIn: "United States" },
  { name: "Amnesty International", description: "Support Human Rights and Freedoms.", logo: "", categories: ["❤️ Charity"], shippingCountries: ["🌍 Worldwide"], website: "https://www.amnesty.org/en/", lightningSupported: false, onchainSupported: true, paymentProvider: "The Giving Block", countryMadeIn: "United States" },
  { name: "Bloom Audio", description: "The most friendly and customer service obsessed store for the world's best audiophile brands", logo: "", categories: ["💻 Electronics"], shippingCountries: ["🌍 Worldwide"], website: "https://bloomaudio.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Open Node", countryMadeIn: "United States" },
  { name: "Bitrefill", description: "Shop for Gift Cards, eSIMs, and Mobile Recharges with BTC", logo: "", categories: ["🎁 Gift Cards", "Cellular"], shippingCountries: ["🌍 Worldwide"], website: "https://www.bitrefill.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Self-hosted", countryMadeIn: "Sweden" },
  { name: "Obscura VPN", description: "\"No-log\" VPNs can track you but we are designed to be provably private, as it is technically impossible for us to see your traffic or logs.", logo: "", categories: ["🛡️ VPN & Privacy", "VPN"], shippingCountries: ["🌍 Worldwide"], website: "https://obscura.net/", lightningSupported: true, onchainSupported: false, paymentProvider: "Self-hosted", countryMadeIn: "United States" },
  { name: "Maxim", description: "Catering to the modern man with content that promises to seduce, entertain and continuously surprise readers.", logo: "", categories: ["Magazine", "Lifestyle"], shippingCountries: ["🌍 Worldwide"], website: "https://www.maxim.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Speed" },
  { name: "Alternative Airlines", description: "Book flights to anywhere in the world on 600+ airlines with 40+ payment methods.", logo: "", categories: ["✈️ Travel"], shippingCountries: ["🌍 Worldwide"], website: "https://www.alternativeairlines.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Coingate" },
  { name: "Grab", description: "The all-in-one platform for rides, delivery, payments and insurance.", logo: "", categories: ["Food Delivery", "Taxi", "Insurance", "Payments"], shippingCountries: ["Singapore"], website: "https://www.grab.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Triple A", countryMadeIn: "Singapore" },
  { name: "LaHaus", description: "Digital real estate marketplace that specializes in the sale of new residential properties in Mexico and Columbia.", logo: "", categories: ["Real Estate"], shippingCountries: ["Mexico", "Columbia"], website: "https://www.lahaus.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Coingate", countryMadeIn: "Columbia" },
  { name: "Super Yachts Monaco", description: "Boutique brokerage headquartered in Monaco and operating globally.", logo: "", categories: ["Yachts"], shippingCountries: [], website: "https://www.superyachtsmonaco.com/", lightningSupported: true, onchainSupported: false, paymentProvider: "Bitcashier", countryMadeIn: "Monaco" },
  { name: "Trade It", description: "Instantly Trade, Buy or Sell CS2, RUST, and TF2 skins for the lowest fees!", logo: "", categories: ["Gaming"], shippingCountries: ["🌍 Worldwide"], website: "https://tradeit.gg/", lightningSupported: true, onchainSupported: true, paymentProvider: "NOWPayments", countryMadeIn: "United States" },
  { name: "OpenSats", description: "Funding free and open-source software and projects, particularly those related to Bitcoin, Nostr, and \"freedom tech,\" including protocol development and privacy tools.", logo: "", categories: ["❤️ Charity"], shippingCountries: ["🌍 Worldwide"], website: "https://opensats.org/", lightningSupported: true, onchainSupported: true, paymentProvider: "BTCPay Server", countryMadeIn: "United States" },
  { name: "Stake", description: "Play the best online casino games, slots & live casino games, or bet on sports", logo: "", categories: ["Gambling"], shippingCountries: ["🌍 Worldwide"], website: "https://stake.com/", lightningSupported: false, onchainSupported: true, paymentProvider: "Self-hosted", countryMadeIn: "Curacoa" },
  { name: "Aqua Living", description: "Discover premium hot tubs, swim spas, and cold tubs.", logo: "", categories: ["Hot Tubs", "Lifestyle"], shippingCountries: ["United States"], website: "https://hottub.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Speed", countryMadeIn: "United States" },
  { name: "Mirai Flights", description: "Instantly book private jets and empty legs worldwide with real-time fixed pricing.", logo: "", categories: ["✈️ Travel"], shippingCountries: ["🌍 Worldwide"], website: "https://mirai.flights/", lightningSupported: false, onchainSupported: true, paymentProvider: "CoinsPaid", countryMadeIn: "United Kingdom" },
  { name: "Rumble", description: "Your rights management video platform. Host, distribute and monetize all your professional, social and viral video.", logo: "", categories: ["Social Media"], shippingCountries: ["🌍 Worldwide"], website: "https://rumble.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Self-hosted", countryMadeIn: "United States" },
  { name: "Primal", description: "Social media app where you control your identity, content and algorithm with the right to exit.", logo: "", categories: ["Social Media"], shippingCountries: ["🌍 Worldwide"], website: "https://primal.net/", lightningSupported: true, onchainSupported: false, paymentProvider: "Strike" },
  { name: "Dope Gallery", description: "A wide selection of prints, sculptures, art toys, photography and original paintings by names such as Takashi Murakami, Banksy, Kaws, Bearbrick, Edgar Plans", logo: "", categories: ["🎨 Art"], shippingCountries: ["🌍 Worldwide"], website: "https://dope.gallery/", lightningSupported: true, onchainSupported: true, paymentProvider: "NOWPayments" },
  { name: "St Judes Children's Research Hospital", description: "A leading children's hospital, St. Jude treats the toughest childhood cancers and pediatric diseases.", logo: "", categories: ["❤️ Charity"], shippingCountries: ["🌍 Worldwide"], website: "https://www.stjude.org/", lightningSupported: false, onchainSupported: true, paymentProvider: "The Giving Block", countryMadeIn: "United States" },
  { name: "Lomonds School", description: "West Scotland's only day and boarding school welcomes families from around the world to enjoy a first-class education and lifestyle", logo: "", categories: ["Education"], shippingCountries: ["United Kingdom"], website: "https://www.lomondschool.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "CoinCorner", countryMadeIn: "United Kingdom" },
  { name: "RPG Stash", description: "Buy Game Items and Services since its launch in 2004.", logo: "", categories: ["Gaming"], shippingCountries: ["🌍 Worldwide"], website: "https://www.rpgstash.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Open Node", countryMadeIn: "United Arab Emirates" },
  { name: "Great Ghee", description: "3rd party lab-tested, grass-fed, pasture-raised, ghee sourced and produced exclusively in Virginia, USA.", logo: "", categories: ["🍴 Food & Drink"], shippingCountries: ["United States"], website: "https://greatghee.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "Strike", countryMadeIn: "United States" },
  { name: "Pika Sim", description: "Privacy-first eSIM for 190+ countries. No account needed.", logo: "", categories: ["Cellular"], shippingCountries: ["🌍 Worldwide"], website: "https://pikasim.com/", lightningSupported: true, onchainSupported: true, paymentProvider: "BTCPay Server" },
];

export async function seed() {
  console.log("Seeding database...");

  const existing = await db.select().from(merchants);
  if (existing.length > 0) {
    console.log(`Database already has ${existing.length} merchants. Skipping seed.`);
    return;
  }

  const today = new Date().toISOString().split('T')[0];
  const merchantsWithDate = SEED_MERCHANTS.map(m => ({ ...m, lastSurveyed: today }));
  await db.insert(merchants).values(merchantsWithDate);
  console.log(`Seeded ${SEED_MERCHANTS.length} merchants.`);
}

const isDirectRun = process.argv[1]?.includes('seed');
if (isDirectRun) {
  seed()
    .then(() => {
      console.log("Seed complete.");
      process.exit(0);
    })
    .catch((err) => {
      console.error("Seed failed:", err);
      process.exit(1);
    });
}
