// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/merchant-directory/AppleStyle.tsx": () => import("../components/mockups/merchant-directory/AppleStyle.tsx"),
  "./components/mockups/merchant-directory/RevolutStyle.tsx": () => import("../components/mockups/merchant-directory/RevolutStyle.tsx")
};
