import { storage } from "../server/storage";
import { MOCK_MERCHANTS } from "../client/src/lib/mock-data";

async function seed() {
  console.log("Starting database seeding...");
  
  const logoMap: Record<string, string> = {
    "BitRefill": "/assets/bitrefill-logo.png",
    "SLNT": "/assets/slnt-logo.png",
    "Mullvad VPN": "/assets/mullvad-logo.png",
    "Coinkite": "/assets/coinkite-logo.png",
    "Start9": "/assets/start9-logo.png",
    "Daylight Computer": "/assets/daylight-logo.png",
    "Tor Project": "/assets/tor-logo-new.png",
    "Namecheap": "/assets/namecheap-logo.png",
    "Human Rights Foundation": "/assets/hrf-logo.png",
    "CheapAir": "/assets/cheapair-logo.png",
    "Travala": "/assets/travala-logo-new.png",
    "G2A": "/assets/g2a-logo-new.png",
    "Obscura": "/assets/obscura-logo-new.png",
    "Silent.link": "/assets/silent-link-logo-new.png",
    "Great Ghee": "/assets/great-ghee-clean.png",
    "Great North Air Ambulance": "/assets/gnaas-logo-new.png",
    "Castle Hill Gin": "/assets/castle-hill-gin-new.png",
    "Bonjour Wines": "/assets/bonjour-wines-new.png",
    "Peony Lane Wine": "/assets/peony-lane-new.png",
    "Yum Yum Tree Fudge": "/assets/yum-yum-tree-fudge-new.png",
    "Tea and Tonic": "/assets/tea-and-tonic-new.png",
    "AroTags": "/assets/arotags-new.png",
    "Spitting Feathers": "/assets/spitting-feathers-fox.png",
    "Mushmore Supplements": "/assets/mushmore-logo.png",
    "Hummingbird Amsterdam": "/assets/hummingbird-logo.png",
    "Planet Express": "/assets/planet-express-logo.png",
    "Farfetch": "/assets/farfetch-logo.png",
    "Bramleigh Farm": "/assets/bramleigh-logo.png",
    "Oshi Good": "/assets/oshi-new.png",
    "Palingshop": "/assets/palingshop-logo.png",
    "Ticketpro": "/assets/ticketpro-logo.png",
    "Dynadot": "/assets/dynadot-logo.png",
    "Soapminer": "/assets/soapminer-logo.png",
    "MobiMatter": "/assets/mobimatter-logo.png",
    "The Good Beans": "/assets/thegoodbeans-logo.png",
    "Pumphreys Coffee": "/assets/pumphreys-logo.png",
    "Epic Deals": "/assets/epicdeals-logo.png",
    "Farmer Bill's Provisions": "/assets/farmerbills-logo.png",
    "Acme Acres": "/assets/acmeacres-logo.png",
    "Chroma": "/assets/chroma-new.png",
    "Kawa": "/assets/kawa-new.png",
    "Kijicha": "/assets/kijicha-new.png",
    "Leeds Gin": "https://www.leedsgin.com/wp-content/uploads/elementor/thumbs/cropped-Favicon-v2-01-plyh4y2k69gla83ozhwxsz3smo2eeooufuj8remsgw.png",
    "ASF Tutoring": "/assets/asf-tutoring-new.png",
    "The Suffolk Tutor": "https://static.wixstatic.com/media/e7f737_461ad44966af488b8bdfee9c8146a001~mv2.png/v1/fill/w_385,h_465,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/%40thesuffolktutor.png",
    "Jimble's Jumble": "https://jimblesjumble.odoo.com/web/image/3369-f7e687f9/3-DSC_0022.webp",
    "Hempful": "/assets/hempful-new.png",
    "Highland Fayre": "/assets/highland-fayre-new.png",
    "Golden Tallow": "/assets/golden-tallow-logo.png",
    "Mister Padel": "/assets/mister-padel-icon.png",
    "Lincoln Kiln Dried Logs": "https://lincolnkilndriedlogs.co.uk/wp-content/uploads/2021/08/cropped-favicon-32x32.png",
    "Essatoshi": "https://essatoshi.com/cdn/shop/files/essatoshi_logo_black_180x.png",
    "Cheerings": "/assets/cheerings-logo-new.png",
    "Jonathan Hill Luthier": "https://jonathanhillguitars.com/wp-content/uploads/2021/04/cropped-favicon-32x32.png",
    "Select Automotive": "https://www.selectautomotive.co.uk/wp-content/uploads/2021/05/cropped-favicon-32x32.png",
    "CandyJets": "https://candyjets.com/wp-content/uploads/2021/05/cropped-favicon-32x32.png",
    "Maple AI": "https://maple.ai/wp-content/uploads/2021/05/cropped-favicon-32x32.png",
    "PayperQ": "https://payperq.com/wp-content/uploads/2021/05/cropped-favicon-32x32.png",
    "Crypto Tax Help": "https://cryptotaxhelp.co.uk/wp-content/uploads/2021/05/cropped-favicon-32x32.png",
    "MtSocks": "https://www.mtsocks.com/static/images/favicon-32x32.png",
    "TorGuard": "https://torguard.net/images/favicon.png",
    "Beef Initiative": "https://beefinitiative.com/cdn/shop/files/BI_Logo_Black_180x.png",
    "Spy Equipment UK": "https://www.spyequipmentuk.co.uk/skin/frontend/spyequipment/default/images/favicon.ico",
    "Bees & Trees": "https://beesandtrees.com/cdn/shop/files/bees-and-trees-logo-black_180x.png",
    "Kaffebox": "https://www.kaffebox.no/wp-content/uploads/2016/06/kaffebox-logo-black-300x111.png",
    "Bloom Audio": "https://bloomaudio.com/cdn/shop/files/bloom-audio-logo-black_180x.png",
    "La Industria Handmade": "/assets/la-industria-logo.png",
    "Campo Apícola": "/assets/campo-apicola-logo.png",
    "Elephant Chateau": "/assets/elephant-chateau-logo.png",
    "Árbol de Maple": "/assets/arbol-de-maple-new.png",
    "Consumer Choice Center": "/assets/ccc-logo-new.png",
    "Pikasim": "/assets/pikasim-new.png",
    "Mad Gringo Hot Sauce": "/assets/mad-gringo-new.png",
    "PrivateRouter": "/assets/privaterouter-new.png",
    "IVPN": "/assets/ivpn-new.png",
    "Hyke & Byke": "/assets/hyke-byke-new.png",
    "Kerwell": "/assets/kerwell-new.png",
    "Sticky": "/assets/sticky-new.png",
    "Samen Maier": "/assets/samen-maier-new.png",
    "Smith Pastures": "/assets/smith-pastures-logo.png",
    "SKOON.": "/assets/skoon-new.png",
    "Mei Leaf": "/assets/mei-leaf-new.png",
    "Missprint": "/assets/missprint-logo.png",
    "Izindlovu": "/assets/izindlovu-logo.png",
    "Sole": "/assets/sole-logo-new.png",
    "FuelingYou": "/assets/fuelingyou-logo-new.png",
    "Root & Branch": "/assets/root-and-branch-new.png",
    "Atoms": "/assets/atoms-new-logo.png",
    "Heatbit": "/assets/heatbit-new.png",
    "NoGood Studio": "/assets/nogood-new.png",
    "DeGoogled": "/assets/degoogled-new.png",
    "Crave": "/assets/crave-new.png",
    "MMOGA": "/assets/mmoga-new.png",
    "Human Trafficking Institute": "/assets/hti-new.png",
    "Uzi Shop": "/assets/uzishop-new.png",
    "Le Cyclo Sportif": "/assets/lecyclosportif-new.png",
    "Hill Helicopters": "/assets/hillhelicopters-new.png",
    "Alternative Airlines": "/assets/alternativeairlines-v2.png",
    "Brazilian Botanicals": "/assets/brazilianbotanicals-v2.png",
    "CyberPiggy": "/assets/cyberpiggy-v2.png",
    "NordVPN": "/assets/nordvpn-v2.png",
    "GameRoom": "/assets/gameroom-v2.png",
    "Hotelgift": "/assets/hotelgift-v2.png",
    "ReachTags": "/assets/reachtags-v2.png",
    "Surfshark": "/assets/surfshark-v2.png",
    "Vintage Guitar World": "/assets/vintage-guitar-v2.png",
    "Wayland Games": "/assets/wayland-games-v2.png",
    "ZenMarket": "/assets/zenmarket-v2.png",
    "Zumub": "/assets/zumub-v2.png",
    "Gift Off": "/assets/giftoff-v2.png",
    "Waking Herbs": "/assets/waking-herbs-v2.png",
    "Freedom of the Press Foundation": "/assets/fotp-v2.png",
    "Internet Archive": "/assets/archive-v2.png"
  };

  console.log("Seeding merchants...");
  for (const merchant of MOCK_MERCHANTS) {
    const { reviews, id, logo, ...merchantData } = merchant;
    const correctLogo = logoMap[merchant.name] || logo;
    const created = await storage.createMerchant({
      ...merchantData,
      logo: correctLogo
    });
    
    for (const review of reviews) {
      const { id: _, ...reviewData } = review;
      await storage.createReview({ ...reviewData, merchantId: created.id });
    }
  }
  console.log("Seed complete!");
}

seed().catch(console.error);
